/* 
 * Intrinio API
 *
 * Welcome to the Intrinio API! Through our Marketplace, we offer a wide selection of financial data feeds sourced by our own proprietary processes as well as from many data vendors. The primary application of the Intrinio API is for use in third-party applications and integrations or for end-users utilizing the Excel add-in and Google Sheets add-on. The Intrinio API uses HTTPS verbs and a RESTful endpoint structure, which makes it easy to request data from Intrinio. Responses are delivered in JSON format. If you need additional help in using the API, go to our home page (https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Intrinio.Client;
using Intrinio.Api;
using Intrinio.Model;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing FilingApi
    /// </summary>
    [TestFixture]
    public class FilingApiTests
    {
        private FilingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FilingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FilingApi
            //Assert.IsInstanceOfType(typeof(FilingApi), instance, "instance is a FilingApi");
        }

        
        /// <summary>
        /// Test FilterFilings
        /// </summary>
        [Test]
        public void FilterFilingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string company = null;
            //string reportType = null;
            //DateTime? startDate = null;
            //DateTime? endDate = null;
            //string nextPage = null;
            //var response = instance.FilterFilings(company, reportType, startDate, endDate, nextPage);
            //Assert.IsInstanceOf<List<Filing>> (response, "response is List<Filing>");
        }
        
        /// <summary>
        /// Test GetAllFilings
        /// </summary>
        [Test]
        public void GetAllFilingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nextPage = null;
            //var response = instance.GetAllFilings(nextPage);
            //Assert.IsInstanceOf<List<Filing>> (response, "response is List<Filing>");
        }
        
        /// <summary>
        /// Test GetFilingById
        /// </summary>
        [Test]
        public void GetFilingByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetFilingById(id);
            //Assert.IsInstanceOf<Filing> (response, "response is Filing");
        }
        
    }

}
