


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing AccountCurrentUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountCurrentUsageTests
    {
        // TODO uncomment below to declare an instance variable for AccountCurrentUsage
        //private AccountCurrentUsage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountCurrentUsage
            //instance = new AccountCurrentUsage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountCurrentUsage
        /// </summary>
        [Test]
        public void AccountCurrentUsageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountCurrentUsage
            //Assert.IsInstanceOfType<AccountCurrentUsage> (instance, "variable 'instance' is a AccountCurrentUsage");
        }


        /// <summary>
        /// Test the property 'AccessCode'
        /// </summary>
        [Test]
        public void AccessCodeTest()
        {
            // TODO unit test for the property 'AccessCode'
        }
        /// <summary>
        /// Test the property 'Restriction'
        /// </summary>
        [Test]
        public void RestrictionTest()
        {
            // TODO unit test for the property 'Restriction'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'SecondsUntilReset'
        /// </summary>
        [Test]
        public void SecondsUntilResetTest()
        {
            // TODO unit test for the property 'SecondsUntilReset'
        }
        /// <summary>
        /// Test the property 'PercentageUsed'
        /// </summary>
        [Test]
        public void PercentageUsedTest()
        {
            // TODO unit test for the property 'PercentageUsed'
        }

    }

}
