


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockExchanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockExchangesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockExchanges
        //private ApiResponseStockExchanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockExchanges
            //instance = new ApiResponseStockExchanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockExchanges
        /// </summary>
        [Test]
        public void ApiResponseStockExchangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockExchanges
            //Assert.IsInstanceOfType<ApiResponseStockExchanges> (instance, "variable 'instance' is a ApiResponseStockExchanges");
        }


        /// <summary>
        /// Test the property 'StockExchanges'
        /// </summary>
        [Test]
        public void StockExchangesTest()
        {
            // TODO unit test for the property 'StockExchanges'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
