


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseSecurityVolumePriceTrend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseSecurityVolumePriceTrendTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseSecurityVolumePriceTrend
        //private ApiResponseSecurityVolumePriceTrend instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseSecurityVolumePriceTrend
            //instance = new ApiResponseSecurityVolumePriceTrend();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseSecurityVolumePriceTrend
        /// </summary>
        [Test]
        public void ApiResponseSecurityVolumePriceTrendInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseSecurityVolumePriceTrend
            //Assert.IsInstanceOfType<ApiResponseSecurityVolumePriceTrend> (instance, "variable 'instance' is a ApiResponseSecurityVolumePriceTrend");
        }


        /// <summary>
        /// Test the property 'Technicals'
        /// </summary>
        [Test]
        public void TechnicalsTest()
        {
            // TODO unit test for the property 'Technicals'
        }
        /// <summary>
        /// Test the property 'Indicator'
        /// </summary>
        [Test]
        public void IndicatorTest()
        {
            // TODO unit test for the property 'Indicator'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
