


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseIndices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseIndicesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseIndices
        //private ApiResponseIndices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseIndices
            //instance = new ApiResponseIndices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseIndices
        /// </summary>
        [Test]
        public void ApiResponseIndicesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseIndices
            //Assert.IsInstanceOfType<ApiResponseIndices> (instance, "variable 'instance' is a ApiResponseIndices");
        }


        /// <summary>
        /// Test the property 'Indices'
        /// </summary>
        [Test]
        public void IndicesTest()
        {
            // TODO unit test for the property 'Indices'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
