


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseIndexIntervals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseIndexIntervalsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseIndexIntervals
        //private ApiResponseIndexIntervals instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseIndexIntervals
            //instance = new ApiResponseIndexIntervals();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseIndexIntervals
        /// </summary>
        [Test]
        public void ApiResponseIndexIntervalsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseIndexIntervals
            //Assert.IsInstanceOfType<ApiResponseIndexIntervals> (instance, "variable 'instance' is a ApiResponseIndexIntervals");
        }


        /// <summary>
        /// Test the property 'Intervals'
        /// </summary>
        [Test]
        public void IntervalsTest()
        {
            // TODO unit test for the property 'Intervals'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
