


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseZacksForwardPEs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseZacksForwardPEsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseZacksForwardPEs
        //private ApiResponseZacksForwardPEs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseZacksForwardPEs
            //instance = new ApiResponseZacksForwardPEs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseZacksForwardPEs
        /// </summary>
        [Test]
        public void ApiResponseZacksForwardPEsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseZacksForwardPEs
            //Assert.IsInstanceOfType<ApiResponseZacksForwardPEs> (instance, "variable 'instance' is a ApiResponseZacksForwardPEs");
        }


        /// <summary>
        /// Test the property 'ForwardPe'
        /// </summary>
        [Test]
        public void ForwardPeTest()
        {
            // TODO unit test for the property 'ForwardPe'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
