


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseAllExpectedEarningsDates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseAllExpectedEarningsDatesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseAllExpectedEarningsDates
        //private ApiResponseAllExpectedEarningsDates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseAllExpectedEarningsDates
            //instance = new ApiResponseAllExpectedEarningsDates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseAllExpectedEarningsDates
        /// </summary>
        [Test]
        public void ApiResponseAllExpectedEarningsDatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseAllExpectedEarningsDates
            //Assert.IsInstanceOfType<ApiResponseAllExpectedEarningsDates> (instance, "variable 'instance' is a ApiResponseAllExpectedEarningsDates");
        }


        /// <summary>
        /// Test the property 'ExpectedEarningsDates'
        /// </summary>
        [Test]
        public void ExpectedEarningsDatesTest()
        {
            // TODO unit test for the property 'ExpectedEarningsDates'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
