


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsChainEod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsChainEodTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsChainEod
        //private ApiResponseOptionsChainEod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsChainEod
            //instance = new ApiResponseOptionsChainEod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsChainEod
        /// </summary>
        [Test]
        public void ApiResponseOptionsChainEodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsChainEod
            //Assert.IsInstanceOfType<ApiResponseOptionsChainEod> (instance, "variable 'instance' is a ApiResponseOptionsChainEod");
        }


        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Test]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }

    }

}
