


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseSecurityTradingStatuses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseSecurityTradingStatusesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseSecurityTradingStatuses
        //private ApiResponseSecurityTradingStatuses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseSecurityTradingStatuses
            //instance = new ApiResponseSecurityTradingStatuses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseSecurityTradingStatuses
        /// </summary>
        [Test]
        public void ApiResponseSecurityTradingStatusesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseSecurityTradingStatuses
            //Assert.IsInstanceOfType<ApiResponseSecurityTradingStatuses> (instance, "variable 'instance' is a ApiResponseSecurityTradingStatuses");
        }


        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Test]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }
        /// <summary>
        /// Test the property 'MarketStatus'
        /// </summary>
        [Test]
        public void MarketStatusTest()
        {
            // TODO unit test for the property 'MarketStatus'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
