


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCompanyPublicFloatResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCompanyPublicFloatResultTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCompanyPublicFloatResult
        //private ApiResponseCompanyPublicFloatResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCompanyPublicFloatResult
            //instance = new ApiResponseCompanyPublicFloatResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCompanyPublicFloatResult
        /// </summary>
        [Test]
        public void ApiResponseCompanyPublicFloatResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCompanyPublicFloatResult
            //Assert.IsInstanceOfType<ApiResponseCompanyPublicFloatResult> (instance, "variable 'instance' is a ApiResponseCompanyPublicFloatResult");
        }


        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'PublicFloats'
        /// </summary>
        [Test]
        public void PublicFloatsTest()
        {
            // TODO unit test for the property 'PublicFloats'
        }

    }

}
