


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCompanyNewsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCompanyNewsBodyTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCompanyNewsBody
        //private ApiResponseCompanyNewsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCompanyNewsBody
            //instance = new ApiResponseCompanyNewsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCompanyNewsBody
        /// </summary>
        [Test]
        public void ApiResponseCompanyNewsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCompanyNewsBody
            //Assert.IsInstanceOfType<ApiResponseCompanyNewsBody> (instance, "variable 'instance' is a ApiResponseCompanyNewsBody");
        }


        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
