


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseSecurityIntervalPrices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseSecurityIntervalPricesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseSecurityIntervalPrices
        //private ApiResponseSecurityIntervalPrices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseSecurityIntervalPrices
            //instance = new ApiResponseSecurityIntervalPrices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseSecurityIntervalPrices
        /// </summary>
        [Test]
        public void ApiResponseSecurityIntervalPricesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseSecurityIntervalPrices
            //Assert.IsInstanceOfType<ApiResponseSecurityIntervalPrices> (instance, "variable 'instance' is a ApiResponseSecurityIntervalPrices");
        }


        /// <summary>
        /// Test the property 'Intervals'
        /// </summary>
        [Test]
        public void IntervalsTest()
        {
            // TODO unit test for the property 'Intervals'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
