


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseZacksEPSSurprises
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseZacksEPSSurprisesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseZacksEPSSurprises
        //private ApiResponseZacksEPSSurprises instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseZacksEPSSurprises
            //instance = new ApiResponseZacksEPSSurprises();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseZacksEPSSurprises
        /// </summary>
        [Test]
        public void ApiResponseZacksEPSSurprisesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseZacksEPSSurprises
            //Assert.IsInstanceOfType<ApiResponseZacksEPSSurprises> (instance, "variable 'instance' is a ApiResponseZacksEPSSurprises");
        }


        /// <summary>
        /// Test the property 'EpsSurprises'
        /// </summary>
        [Test]
        public void EpsSurprisesTest()
        {
            // TODO unit test for the property 'EpsSurprises'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
