


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseZacksEPSEstimates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseZacksEPSEstimatesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseZacksEPSEstimates
        //private ApiResponseZacksEPSEstimates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseZacksEPSEstimates
            //instance = new ApiResponseZacksEPSEstimates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseZacksEPSEstimates
        /// </summary>
        [Test]
        public void ApiResponseZacksEPSEstimatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseZacksEPSEstimates
            //Assert.IsInstanceOfType<ApiResponseZacksEPSEstimates> (instance, "variable 'instance' is a ApiResponseZacksEPSEstimates");
        }


        /// <summary>
        /// Test the property 'Estimates'
        /// </summary>
        [Test]
        public void EstimatesTest()
        {
            // TODO unit test for the property 'Estimates'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
