


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCryptoPairs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCryptoPairsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCryptoPairs
        //private ApiResponseCryptoPairs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCryptoPairs
            //instance = new ApiResponseCryptoPairs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCryptoPairs
        /// </summary>
        [Test]
        public void ApiResponseCryptoPairsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCryptoPairs
            //Assert.IsInstanceOfType<ApiResponseCryptoPairs> (instance, "variable 'instance' is a ApiResponseCryptoPairs");
        }


        /// <summary>
        /// Test the property 'Pairs'
        /// </summary>
        [Test]
        public void PairsTest()
        {
            // TODO unit test for the property 'Pairs'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
