


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseAccountUsages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseAccountUsagesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseAccountUsages
        //private ApiResponseAccountUsages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseAccountUsages
            //instance = new ApiResponseAccountUsages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseAccountUsages
        /// </summary>
        [Test]
        public void ApiResponseAccountUsagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseAccountUsages
            //Assert.IsInstanceOfType<ApiResponseAccountUsages> (instance, "variable 'instance' is a ApiResponseAccountUsages");
        }


        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Test]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

    }

}
