


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockExchangeRealtimeStockPrices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockExchangeRealtimeStockPricesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockExchangeRealtimeStockPrices
        //private ApiResponseStockExchangeRealtimeStockPrices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockExchangeRealtimeStockPrices
            //instance = new ApiResponseStockExchangeRealtimeStockPrices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockExchangeRealtimeStockPrices
        /// </summary>
        [Test]
        public void ApiResponseStockExchangeRealtimeStockPricesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockExchangeRealtimeStockPrices
            //Assert.IsInstanceOfType<ApiResponseStockExchangeRealtimeStockPrices> (instance, "variable 'instance' is a ApiResponseStockExchangeRealtimeStockPrices");
        }


        /// <summary>
        /// Test the property 'StockPrices'
        /// </summary>
        [Test]
        public void StockPricesTest()
        {
            // TODO unit test for the property 'StockPrices'
        }
        /// <summary>
        /// Test the property 'StockExchange'
        /// </summary>
        [Test]
        public void StockExchangeTest()
        {
            // TODO unit test for the property 'StockExchange'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
