


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCryptoExchanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCryptoExchangesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCryptoExchanges
        //private ApiResponseCryptoExchanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCryptoExchanges
            //instance = new ApiResponseCryptoExchanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCryptoExchanges
        /// </summary>
        [Test]
        public void ApiResponseCryptoExchangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCryptoExchanges
            //Assert.IsInstanceOfType<ApiResponseCryptoExchanges> (instance, "variable 'instance' is a ApiResponseCryptoExchanges");
        }


        /// <summary>
        /// Test the property 'Exchanges'
        /// </summary>
        [Test]
        public void ExchangesTest()
        {
            // TODO unit test for the property 'Exchanges'
        }

    }

}
