


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseAccountUsagesAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseAccountUsagesAccountTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseAccountUsagesAccount
        //private ApiResponseAccountUsagesAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseAccountUsagesAccount
            //instance = new ApiResponseAccountUsagesAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseAccountUsagesAccount
        /// </summary>
        [Test]
        public void ApiResponseAccountUsagesAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseAccountUsagesAccount
            //Assert.IsInstanceOfType<ApiResponseAccountUsagesAccount> (instance, "variable 'instance' is a ApiResponseAccountUsagesAccount");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
