


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseMunicipalitiyFinancials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseMunicipalitiyFinancialsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseMunicipalitiyFinancials
        //private ApiResponseMunicipalitiyFinancials instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseMunicipalitiyFinancials
            //instance = new ApiResponseMunicipalitiyFinancials();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseMunicipalitiyFinancials
        /// </summary>
        [Test]
        public void ApiResponseMunicipalitiyFinancialsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseMunicipalitiyFinancials
            //Assert.IsInstanceOfType<ApiResponseMunicipalitiyFinancials> (instance, "variable 'instance' is a ApiResponseMunicipalitiyFinancials");
        }


        /// <summary>
        /// Test the property 'Financials'
        /// </summary>
        [Test]
        public void FinancialsTest()
        {
            // TODO unit test for the property 'Financials'
        }
        /// <summary>
        /// Test the property 'Municipality'
        /// </summary>
        [Test]
        public void MunicipalityTest()
        {
            // TODO unit test for the property 'Municipality'
        }

    }

}
