


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsPricesByTickerRealtime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsPricesByTickerRealtimeTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsPricesByTickerRealtime
        //private ApiResponseOptionsPricesByTickerRealtime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsPricesByTickerRealtime
            //instance = new ApiResponseOptionsPricesByTickerRealtime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsPricesByTickerRealtime
        /// </summary>
        [Test]
        public void ApiResponseOptionsPricesByTickerRealtimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsPricesByTickerRealtime
            //Assert.IsInstanceOfType<ApiResponseOptionsPricesByTickerRealtime> (instance, "variable 'instance' is a ApiResponseOptionsPricesByTickerRealtime");
        }


        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'Contracts'
        /// </summary>
        [Test]
        public void ContractsTest()
        {
            // TODO unit test for the property 'Contracts'
        }

    }

}
