


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCryptoSnapshot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCryptoSnapshotTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCryptoSnapshot
        //private ApiResponseCryptoSnapshot instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCryptoSnapshot
            //instance = new ApiResponseCryptoSnapshot();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCryptoSnapshot
        /// </summary>
        [Test]
        public void ApiResponseCryptoSnapshotInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCryptoSnapshot
            //Assert.IsInstanceOfType<ApiResponseCryptoSnapshot> (instance, "variable 'instance' is a ApiResponseCryptoSnapshot");
        }


        /// <summary>
        /// Test the property 'Pair'
        /// </summary>
        [Test]
        public void PairTest()
        {
            // TODO unit test for the property 'Pair'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Snapshot'
        /// </summary>
        [Test]
        public void SnapshotTest()
        {
            // TODO unit test for the property 'Snapshot'
        }

    }

}
