


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsTickers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsTickersTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsTickers
        //private ApiResponseOptionsTickers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsTickers
            //instance = new ApiResponseOptionsTickers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsTickers
        /// </summary>
        [Test]
        public void ApiResponseOptionsTickersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsTickers
            //Assert.IsInstanceOfType<ApiResponseOptionsTickers> (instance, "variable 'instance' is a ApiResponseOptionsTickers");
        }


        /// <summary>
        /// Test the property 'Tickers'
        /// </summary>
        [Test]
        public void TickersTest()
        {
            // TODO unit test for the property 'Tickers'
        }

    }

}
