


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCryptoSimpleMovingAverage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCryptoSimpleMovingAverageTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCryptoSimpleMovingAverage
        //private ApiResponseCryptoSimpleMovingAverage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCryptoSimpleMovingAverage
            //instance = new ApiResponseCryptoSimpleMovingAverage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCryptoSimpleMovingAverage
        /// </summary>
        [Test]
        public void ApiResponseCryptoSimpleMovingAverageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCryptoSimpleMovingAverage
            //Assert.IsInstanceOfType<ApiResponseCryptoSimpleMovingAverage> (instance, "variable 'instance' is a ApiResponseCryptoSimpleMovingAverage");
        }


        /// <summary>
        /// Test the property 'Technicals'
        /// </summary>
        [Test]
        public void TechnicalsTest()
        {
            // TODO unit test for the property 'Technicals'
        }
        /// <summary>
        /// Test the property 'Indicator'
        /// </summary>
        [Test]
        public void IndicatorTest()
        {
            // TODO unit test for the property 'Indicator'
        }
        /// <summary>
        /// Test the property 'Pair'
        /// </summary>
        [Test]
        public void PairTest()
        {
            // TODO unit test for the property 'Pair'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Timeframe'
        /// </summary>
        [Test]
        public void TimeframeTest()
        {
            // TODO unit test for the property 'Timeframe'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
