


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockExchangeQuote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockExchangeQuoteTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockExchangeQuote
        //private ApiResponseStockExchangeQuote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockExchangeQuote
            //instance = new ApiResponseStockExchangeQuote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockExchangeQuote
        /// </summary>
        [Test]
        public void ApiResponseStockExchangeQuoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockExchangeQuote
            //Assert.IsInstanceOfType<ApiResponseStockExchangeQuote> (instance, "variable 'instance' is a ApiResponseStockExchangeQuote");
        }


        /// <summary>
        /// Test the property 'Quotes'
        /// </summary>
        [Test]
        public void QuotesTest()
        {
            // TODO unit test for the property 'Quotes'
        }
        /// <summary>
        /// Test the property 'StockExchange'
        /// </summary>
        [Test]
        public void StockExchangeTest()
        {
            // TODO unit test for the property 'StockExchange'
        }

    }

}
