


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockMarketIndicesSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockMarketIndicesSearchTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockMarketIndicesSearch
        //private ApiResponseStockMarketIndicesSearch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockMarketIndicesSearch
            //instance = new ApiResponseStockMarketIndicesSearch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockMarketIndicesSearch
        /// </summary>
        [Test]
        public void ApiResponseStockMarketIndicesSearchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockMarketIndicesSearch
            //Assert.IsInstanceOfType<ApiResponseStockMarketIndicesSearch> (instance, "variable 'instance' is a ApiResponseStockMarketIndicesSearch");
        }


        /// <summary>
        /// Test the property 'Indices'
        /// </summary>
        [Test]
        public void IndicesTest()
        {
            // TODO unit test for the property 'Indices'
        }

    }

}
