


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockExchangeMovers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockExchangeMoversTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockExchangeMovers
        //private ApiResponseStockExchangeMovers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockExchangeMovers
            //instance = new ApiResponseStockExchangeMovers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockExchangeMovers
        /// </summary>
        [Test]
        public void ApiResponseStockExchangeMoversInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockExchangeMovers
            //Assert.IsInstanceOfType<ApiResponseStockExchangeMovers> (instance, "variable 'instance' is a ApiResponseStockExchangeMovers");
        }


        /// <summary>
        /// Test the property 'Movers'
        /// </summary>
        [Test]
        public void MoversTest()
        {
            // TODO unit test for the property 'Movers'
        }
        /// <summary>
        /// Test the property 'StockExchange'
        /// </summary>
        [Test]
        public void StockExchangeTest()
        {
            // TODO unit test for the property 'StockExchange'
        }

    }

}
