


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseStockExchangeSecurities
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseStockExchangeSecuritiesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseStockExchangeSecurities
        //private ApiResponseStockExchangeSecurities instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseStockExchangeSecurities
            //instance = new ApiResponseStockExchangeSecurities();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseStockExchangeSecurities
        /// </summary>
        [Test]
        public void ApiResponseStockExchangeSecuritiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseStockExchangeSecurities
            //Assert.IsInstanceOfType<ApiResponseStockExchangeSecurities> (instance, "variable 'instance' is a ApiResponseStockExchangeSecurities");
        }


        /// <summary>
        /// Test the property 'Securities'
        /// </summary>
        [Test]
        public void SecuritiesTest()
        {
            // TODO unit test for the property 'Securities'
        }
        /// <summary>
        /// Test the property 'StockExchange'
        /// </summary>
        [Test]
        public void StockExchangeTest()
        {
            // TODO unit test for the property 'StockExchange'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
