


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseEodIndexPrices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseEodIndexPricesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseEodIndexPrices
        //private ApiResponseEodIndexPrices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseEodIndexPrices
            //instance = new ApiResponseEodIndexPrices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseEodIndexPrices
        /// </summary>
        [Test]
        public void ApiResponseEodIndexPricesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseEodIndexPrices
            //Assert.IsInstanceOfType<ApiResponseEodIndexPrices> (instance, "variable 'instance' is a ApiResponseEodIndexPrices");
        }


        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Test]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
