


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCompanySharesOutstanding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCompanySharesOutstandingTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCompanySharesOutstanding
        //private ApiResponseCompanySharesOutstanding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCompanySharesOutstanding
            //instance = new ApiResponseCompanySharesOutstanding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCompanySharesOutstanding
        /// </summary>
        [Test]
        public void ApiResponseCompanySharesOutstandingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCompanySharesOutstanding
            //Assert.IsInstanceOfType<ApiResponseCompanySharesOutstanding> (instance, "variable 'instance' is a ApiResponseCompanySharesOutstanding");
        }


        /// <summary>
        /// Test the property 'SharesOutstanding'
        /// </summary>
        [Test]
        public void SharesOutstandingTest()
        {
            // TODO unit test for the property 'SharesOutstanding'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

    }

}
