


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsStatsRealtime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsStatsRealtimeTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsStatsRealtime
        //private ApiResponseOptionsStatsRealtime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsStatsRealtime
            //instance = new ApiResponseOptionsStatsRealtime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsStatsRealtime
        /// </summary>
        [Test]
        public void ApiResponseOptionsStatsRealtimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsStatsRealtime
            //Assert.IsInstanceOfType<ApiResponseOptionsStatsRealtime> (instance, "variable 'instance' is a ApiResponseOptionsStatsRealtime");
        }


        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Factors'
        /// </summary>
        [Test]
        public void FactorsTest()
        {
            // TODO unit test for the property 'Factors'
        }
        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Test]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }

    }

}
