


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsPriceRealtime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsPriceRealtimeTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsPriceRealtime
        //private ApiResponseOptionsPriceRealtime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsPriceRealtime
            //instance = new ApiResponseOptionsPriceRealtime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsPriceRealtime
        /// </summary>
        [Test]
        public void ApiResponseOptionsPriceRealtimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsPriceRealtime
            //Assert.IsInstanceOfType<ApiResponseOptionsPriceRealtime> (instance, "variable 'instance' is a ApiResponseOptionsPriceRealtime");
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Test]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }

    }

}
