


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseSecurityZacksEPSSurprises
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseSecurityZacksEPSSurprisesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseSecurityZacksEPSSurprises
        //private ApiResponseSecurityZacksEPSSurprises instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseSecurityZacksEPSSurprises
            //instance = new ApiResponseSecurityZacksEPSSurprises();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseSecurityZacksEPSSurprises
        /// </summary>
        [Test]
        public void ApiResponseSecurityZacksEPSSurprisesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseSecurityZacksEPSSurprises
            //Assert.IsInstanceOfType<ApiResponseSecurityZacksEPSSurprises> (instance, "variable 'instance' is a ApiResponseSecurityZacksEPSSurprises");
        }


        /// <summary>
        /// Test the property 'EpsSurprises'
        /// </summary>
        [Test]
        public void EpsSurprisesTest()
        {
            // TODO unit test for the property 'EpsSurprises'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
