


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseCompanyAnswers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseCompanyAnswersTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseCompanyAnswers
        //private ApiResponseCompanyAnswers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseCompanyAnswers
            //instance = new ApiResponseCompanyAnswers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseCompanyAnswers
        /// </summary>
        [Test]
        public void ApiResponseCompanyAnswersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseCompanyAnswers
            //Assert.IsInstanceOfType<ApiResponseCompanyAnswers> (instance, "variable 'instance' is a ApiResponseCompanyAnswers");
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'Answers'
        /// </summary>
        [Test]
        public void AnswersTest()
        {
            // TODO unit test for the property 'Answers'
        }
        /// <summary>
        /// Test the property 'Companies'
        /// </summary>
        [Test]
        public void CompaniesTest()
        {
            // TODO unit test for the property 'Companies'
        }

    }

}
