


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseOptionsImpliedMove
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseOptionsImpliedMoveTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseOptionsImpliedMove
        //private ApiResponseOptionsImpliedMove instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseOptionsImpliedMove
            //instance = new ApiResponseOptionsImpliedMove();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseOptionsImpliedMove
        /// </summary>
        [Test]
        public void ApiResponseOptionsImpliedMoveInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseOptionsImpliedMove
            //Assert.IsInstanceOfType<ApiResponseOptionsImpliedMove> (instance, "variable 'instance' is a ApiResponseOptionsImpliedMove");
        }


        /// <summary>
        /// Test the property 'ImpliedMove'
        /// </summary>
        [Test]
        public void ImpliedMoveTest()
        {
            // TODO unit test for the property 'ImpliedMove'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'UnderlyingPrice'
        /// </summary>
        [Test]
        public void UnderlyingPriceTest()
        {
            // TODO unit test for the property 'UnderlyingPrice'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
        /// <summary>
        /// Test the property 'AtmStrike'
        /// </summary>
        [Test]
        public void AtmStrikeTest()
        {
            // TODO unit test for the property 'AtmStrike'
        }
        /// <summary>
        /// Test the property 'StraddlePrice'
        /// </summary>
        [Test]
        public void StraddlePriceTest()
        {
            // TODO unit test for the property 'StraddlePrice'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

    }

}
