


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseInsiderTransactionFilings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseInsiderTransactionFilingsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseInsiderTransactionFilings
        //private ApiResponseInsiderTransactionFilings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseInsiderTransactionFilings
            //instance = new ApiResponseInsiderTransactionFilings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseInsiderTransactionFilings
        /// </summary>
        [Test]
        public void ApiResponseInsiderTransactionFilingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseInsiderTransactionFilings
            //Assert.IsInstanceOfType<ApiResponseInsiderTransactionFilings> (instance, "variable 'instance' is a ApiResponseInsiderTransactionFilings");
        }


        /// <summary>
        /// Test the property 'TransactionFilings'
        /// </summary>
        [Test]
        public void TransactionFilingsTest()
        {
            // TODO unit test for the property 'TransactionFilings'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
