


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseRealtimeIndexPrices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseRealtimeIndexPricesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseRealtimeIndexPrices
        //private ApiResponseRealtimeIndexPrices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseRealtimeIndexPrices
            //instance = new ApiResponseRealtimeIndexPrices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseRealtimeIndexPrices
        /// </summary>
        [Test]
        public void ApiResponseRealtimeIndexPricesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseRealtimeIndexPrices
            //Assert.IsInstanceOfType<ApiResponseRealtimeIndexPrices> (instance, "variable 'instance' is a ApiResponseRealtimeIndexPrices");
        }


        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Test]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
