


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseBulkDownloadLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseBulkDownloadLinksTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseBulkDownloadLinks
        //private ApiResponseBulkDownloadLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseBulkDownloadLinks
            //instance = new ApiResponseBulkDownloadLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseBulkDownloadLinks
        /// </summary>
        [Test]
        public void ApiResponseBulkDownloadLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseBulkDownloadLinks
            //Assert.IsInstanceOfType<ApiResponseBulkDownloadLinks> (instance, "variable 'instance' is a ApiResponseBulkDownloadLinks");
        }


        /// <summary>
        /// Test the property 'BulkDownloads'
        /// </summary>
        [Test]
        public void BulkDownloadsTest()
        {
            // TODO unit test for the property 'BulkDownloads'
        }

    }

}
