


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseIndexConstituents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseIndexConstituentsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseIndexConstituents
        //private ApiResponseIndexConstituents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseIndexConstituents
            //instance = new ApiResponseIndexConstituents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseIndexConstituents
        /// </summary>
        [Test]
        public void ApiResponseIndexConstituentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseIndexConstituents
            //Assert.IsInstanceOfType<ApiResponseIndexConstituents> (instance, "variable 'instance' is a ApiResponseIndexConstituents");
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Constituents'
        /// </summary>
        [Test]
        public void ConstituentsTest()
        {
            // TODO unit test for the property 'Constituents'
        }

    }

}
