


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseDataTagsSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseDataTagsSearchTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseDataTagsSearch
        //private ApiResponseDataTagsSearch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseDataTagsSearch
            //instance = new ApiResponseDataTagsSearch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseDataTagsSearch
        /// </summary>
        [Test]
        public void ApiResponseDataTagsSearchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseDataTagsSearch
            //Assert.IsInstanceOfType<ApiResponseDataTagsSearch> (instance, "variable 'instance' is a ApiResponseDataTagsSearch");
        }


        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
