


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ApiResponseZacksInstitutionalHoldingCompanies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseZacksInstitutionalHoldingCompaniesTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseZacksInstitutionalHoldingCompanies
        //private ApiResponseZacksInstitutionalHoldingCompanies instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseZacksInstitutionalHoldingCompanies
            //instance = new ApiResponseZacksInstitutionalHoldingCompanies();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseZacksInstitutionalHoldingCompanies
        /// </summary>
        [Test]
        public void ApiResponseZacksInstitutionalHoldingCompaniesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseZacksInstitutionalHoldingCompanies
            //Assert.IsInstanceOfType<ApiResponseZacksInstitutionalHoldingCompanies> (instance, "variable 'instance' is a ApiResponseZacksInstitutionalHoldingCompanies");
        }


        /// <summary>
        /// Test the property 'Companies'
        /// </summary>
        [Test]
        public void CompaniesTest()
        {
            // TODO unit test for the property 'Companies'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
