


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing AwesomeOscillatorTechnicalValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AwesomeOscillatorTechnicalValueTests
    {
        // TODO uncomment below to declare an instance variable for AwesomeOscillatorTechnicalValue
        //private AwesomeOscillatorTechnicalValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AwesomeOscillatorTechnicalValue
            //instance = new AwesomeOscillatorTechnicalValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AwesomeOscillatorTechnicalValue
        /// </summary>
        [Test]
        public void AwesomeOscillatorTechnicalValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AwesomeOscillatorTechnicalValue
            //Assert.IsInstanceOfType<AwesomeOscillatorTechnicalValue> (instance, "variable 'instance' is a AwesomeOscillatorTechnicalValue");
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Ao'
        /// </summary>
        [Test]
        public void AoTest()
        {
            // TODO unit test for the property 'Ao'
        }

    }

}
