


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ChaikinMoneyFlowTechnicalValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChaikinMoneyFlowTechnicalValueTests
    {
        // TODO uncomment below to declare an instance variable for ChaikinMoneyFlowTechnicalValue
        //private ChaikinMoneyFlowTechnicalValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChaikinMoneyFlowTechnicalValue
            //instance = new ChaikinMoneyFlowTechnicalValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChaikinMoneyFlowTechnicalValue
        /// </summary>
        [Test]
        public void ChaikinMoneyFlowTechnicalValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChaikinMoneyFlowTechnicalValue
            //Assert.IsInstanceOfType<ChaikinMoneyFlowTechnicalValue> (instance, "variable 'instance' is a ChaikinMoneyFlowTechnicalValue");
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Cmf'
        /// </summary>
        [Test]
        public void CmfTest()
        {
            // TODO unit test for the property 'Cmf'
        }

    }

}
