


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CompanyNewsSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompanyNewsSummaryTests
    {
        // TODO uncomment below to declare an instance variable for CompanyNewsSummary
        //private CompanyNewsSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompanyNewsSummary
            //instance = new CompanyNewsSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompanyNewsSummary
        /// </summary>
        [Test]
        public void CompanyNewsSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompanyNewsSummary
            //Assert.IsInstanceOfType<CompanyNewsSummary> (instance, "variable 'instance' is a CompanyNewsSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Test]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }
        /// <summary>
        /// Test the property 'Companies'
        /// </summary>
        [Test]
        public void CompaniesTest()
        {
            // TODO unit test for the property 'Companies'
        }
        /// <summary>
        /// Test the property 'Securities'
        /// </summary>
        [Test]
        public void SecuritiesTest()
        {
            // TODO unit test for the property 'Securities'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Test]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }
        /// <summary>
        /// Test the property 'Copyright'
        /// </summary>
        [Test]
        public void CopyrightTest()
        {
            // TODO unit test for the property 'Copyright'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'WordCount'
        /// </summary>
        [Test]
        public void WordCountTest()
        {
            // TODO unit test for the property 'WordCount'
        }
        /// <summary>
        /// Test the property 'Spam'
        /// </summary>
        [Test]
        public void SpamTest()
        {
            // TODO unit test for the property 'Spam'
        }
        /// <summary>
        /// Test the property 'BusinessRelevance'
        /// </summary>
        [Test]
        public void BusinessRelevanceTest()
        {
            // TODO unit test for the property 'BusinessRelevance'
        }
        /// <summary>
        /// Test the property 'ArticleSentiment'
        /// </summary>
        [Test]
        public void ArticleSentimentTest()
        {
            // TODO unit test for the property 'ArticleSentiment'
        }
        /// <summary>
        /// Test the property 'ArticleSentimentConfidence'
        /// </summary>
        [Test]
        public void ArticleSentimentConfidenceTest()
        {
            // TODO unit test for the property 'ArticleSentimentConfidence'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Test]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'IssuerName'
        /// </summary>
        [Test]
        public void IssuerNameTest()
        {
            // TODO unit test for the property 'IssuerName'
        }
        /// <summary>
        /// Test the property 'IssuerCompany'
        /// </summary>
        [Test]
        public void IssuerCompanyTest()
        {
            // TODO unit test for the property 'IssuerCompany'
        }
        /// <summary>
        /// Test the property 'IssuerSecurity'
        /// </summary>
        [Test]
        public void IssuerSecurityTest()
        {
            // TODO unit test for the property 'IssuerSecurity'
        }

    }

}
