


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CompanySharesOutstanding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompanySharesOutstandingTests
    {
        // TODO uncomment below to declare an instance variable for CompanySharesOutstanding
        //private CompanySharesOutstanding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompanySharesOutstanding
            //instance = new CompanySharesOutstanding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompanySharesOutstanding
        /// </summary>
        [Test]
        public void CompanySharesOutstandingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompanySharesOutstanding
            //Assert.IsInstanceOfType<CompanySharesOutstanding> (instance, "variable 'instance' is a CompanySharesOutstanding");
        }


        /// <summary>
        /// Test the property 'XbrlAxis'
        /// </summary>
        [Test]
        public void XbrlAxisTest()
        {
            // TODO unit test for the property 'XbrlAxis'
        }
        /// <summary>
        /// Test the property 'XbrlMember'
        /// </summary>
        [Test]
        public void XbrlMemberTest()
        {
            // TODO unit test for the property 'XbrlMember'
        }
        /// <summary>
        /// Test the property 'TitleOfSecurity'
        /// </summary>
        [Test]
        public void TitleOfSecurityTest()
        {
            // TODO unit test for the property 'TitleOfSecurity'
        }
        /// <summary>
        /// Test the property 'TradingSymbol'
        /// </summary>
        [Test]
        public void TradingSymbolTest()
        {
            // TODO unit test for the property 'TradingSymbol'
        }
        /// <summary>
        /// Test the property 'SecurityExchangeName'
        /// </summary>
        [Test]
        public void SecurityExchangeNameTest()
        {
            // TODO unit test for the property 'SecurityExchangeName'
        }
        /// <summary>
        /// Test the property 'SharesOutstanding'
        /// </summary>
        [Test]
        public void SharesOutstandingTest()
        {
            // TODO unit test for the property 'SharesOutstanding'
        }

    }

}
