


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CompanyDailyMetric
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompanyDailyMetricTests
    {
        // TODO uncomment below to declare an instance variable for CompanyDailyMetric
        //private CompanyDailyMetric instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompanyDailyMetric
            //instance = new CompanyDailyMetric();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompanyDailyMetric
        /// </summary>
        [Test]
        public void CompanyDailyMetricInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompanyDailyMetric
            //Assert.IsInstanceOfType<CompanyDailyMetric> (instance, "variable 'instance' is a CompanyDailyMetric");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'EnterpriseValue'
        /// </summary>
        [Test]
        public void EnterpriseValueTest()
        {
            // TODO unit test for the property 'EnterpriseValue'
        }
        /// <summary>
        /// Test the property 'EvToEbit'
        /// </summary>
        [Test]
        public void EvToEbitTest()
        {
            // TODO unit test for the property 'EvToEbit'
        }
        /// <summary>
        /// Test the property 'EvToEbitda'
        /// </summary>
        [Test]
        public void EvToEbitdaTest()
        {
            // TODO unit test for the property 'EvToEbitda'
        }
        /// <summary>
        /// Test the property 'MarketCap'
        /// </summary>
        [Test]
        public void MarketCapTest()
        {
            // TODO unit test for the property 'MarketCap'
        }
        /// <summary>
        /// Test the property 'PriceToBook'
        /// </summary>
        [Test]
        public void PriceToBookTest()
        {
            // TODO unit test for the property 'PriceToBook'
        }
        /// <summary>
        /// Test the property 'PriceToEarnings'
        /// </summary>
        [Test]
        public void PriceToEarningsTest()
        {
            // TODO unit test for the property 'PriceToEarnings'
        }
        /// <summary>
        /// Test the property 'PriceToRevenue'
        /// </summary>
        [Test]
        public void PriceToRevenueTest()
        {
            // TODO unit test for the property 'PriceToRevenue'
        }
        /// <summary>
        /// Test the property 'PriceToTangibleBook'
        /// </summary>
        [Test]
        public void PriceToTangibleBookTest()
        {
            // TODO unit test for the property 'PriceToTangibleBook'
        }
        /// <summary>
        /// Test the property 'DividendYield'
        /// </summary>
        [Test]
        public void DividendYieldTest()
        {
            // TODO unit test for the property 'DividendYield'
        }
        /// <summary>
        /// Test the property 'EarningsYield'
        /// </summary>
        [Test]
        public void EarningsYieldTest()
        {
            // TODO unit test for the property 'EarningsYield'
        }
        /// <summary>
        /// Test the property 'EvToInvestedCapital'
        /// </summary>
        [Test]
        public void EvToInvestedCapitalTest()
        {
            // TODO unit test for the property 'EvToInvestedCapital'
        }
        /// <summary>
        /// Test the property 'EvToRevenue'
        /// </summary>
        [Test]
        public void EvToRevenueTest()
        {
            // TODO unit test for the property 'EvToRevenue'
        }
        /// <summary>
        /// Test the property 'EvToNopat'
        /// </summary>
        [Test]
        public void EvToNopatTest()
        {
            // TODO unit test for the property 'EvToNopat'
        }
        /// <summary>
        /// Test the property 'EvToOcf'
        /// </summary>
        [Test]
        public void EvToOcfTest()
        {
            // TODO unit test for the property 'EvToOcf'
        }
        /// <summary>
        /// Test the property 'EvToFcff'
        /// </summary>
        [Test]
        public void EvToFcffTest()
        {
            // TODO unit test for the property 'EvToFcff'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

    }

}
