


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CryptoStat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CryptoStatTests
    {
        // TODO uncomment below to declare an instance variable for CryptoStat
        //private CryptoStat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CryptoStat
            //instance = new CryptoStat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CryptoStat
        /// </summary>
        [Test]
        public void CryptoStatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoStat
            //Assert.IsInstanceOfType<CryptoStat> (instance, "variable 'instance' is a CryptoStat");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'MarketCapUsd'
        /// </summary>
        [Test]
        public void MarketCapUsdTest()
        {
            // TODO unit test for the property 'MarketCapUsd'
        }
        /// <summary>
        /// Test the property 'AvailableSupply'
        /// </summary>
        [Test]
        public void AvailableSupplyTest()
        {
            // TODO unit test for the property 'AvailableSupply'
        }
        /// <summary>
        /// Test the property 'TotalSupply'
        /// </summary>
        [Test]
        public void TotalSupplyTest()
        {
            // TODO unit test for the property 'TotalSupply'
        }
        /// <summary>
        /// Test the property 'MaxSupply'
        /// </summary>
        [Test]
        public void MaxSupplyTest()
        {
            // TODO unit test for the property 'MaxSupply'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }

    }

}
