


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CryptoPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CryptoPriceTests
    {
        // TODO uncomment below to declare an instance variable for CryptoPrice
        //private CryptoPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CryptoPrice
            //instance = new CryptoPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CryptoPrice
        /// </summary>
        [Test]
        public void CryptoPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoPrice
            //Assert.IsInstanceOfType<CryptoPrice> (instance, "variable 'instance' is a CryptoPrice");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Test]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Test]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Test]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Test]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }

    }

}
