


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing CryptoExchange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CryptoExchangeTests
    {
        // TODO uncomment below to declare an instance variable for CryptoExchange
        //private CryptoExchange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CryptoExchange
            //instance = new CryptoExchange();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CryptoExchange
        /// </summary>
        [Test]
        public void CryptoExchangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoExchange
            //Assert.IsInstanceOfType<CryptoExchange> (instance, "variable 'instance' is a CryptoExchange");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'BookDepthAvailable'
        /// </summary>
        [Test]
        public void BookDepthAvailableTest()
        {
            // TODO unit test for the property 'BookDepthAvailable'
        }
        /// <summary>
        /// Test the property 'HistoryAvailable'
        /// </summary>
        [Test]
        public void HistoryAvailableTest()
        {
            // TODO unit test for the property 'HistoryAvailable'
        }
        /// <summary>
        /// Test the property 'SnapshotAvailable'
        /// </summary>
        [Test]
        public void SnapshotAvailableTest()
        {
            // TODO unit test for the property 'SnapshotAvailable'
        }
        /// <summary>
        /// Test the property 'TradesAvailable'
        /// </summary>
        [Test]
        public void TradesAvailableTest()
        {
            // TODO unit test for the property 'TradesAvailable'
        }

    }

}
