


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing DividendRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DividendRecordTests
    {
        // TODO uncomment below to declare an instance variable for DividendRecord
        //private DividendRecord instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DividendRecord
            //instance = new DividendRecord();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DividendRecord
        /// </summary>
        [Test]
        public void DividendRecordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DividendRecord
            //Assert.IsInstanceOfType<DividendRecord> (instance, "variable 'instance' is a DividendRecord");
        }


        /// <summary>
        /// Test the property 'ExDividend'
        /// </summary>
        [Test]
        public void ExDividendTest()
        {
            // TODO unit test for the property 'ExDividend'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'AnnouncementDate'
        /// </summary>
        [Test]
        public void AnnouncementDateTest()
        {
            // TODO unit test for the property 'AnnouncementDate'
        }
        /// <summary>
        /// Test the property 'RecordDate'
        /// </summary>
        [Test]
        public void RecordDateTest()
        {
            // TODO unit test for the property 'RecordDate'
        }
        /// <summary>
        /// Test the property 'PayDate'
        /// </summary>
        [Test]
        public void PayDateTest()
        {
            // TODO unit test for the property 'PayDate'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ForwardYield'
        /// </summary>
        [Test]
        public void ForwardYieldTest()
        {
            // TODO unit test for the property 'ForwardYield'
        }
        /// <summary>
        /// Test the property 'ForwardRate'
        /// </summary>
        [Test]
        public void ForwardRateTest()
        {
            // TODO unit test for the property 'ForwardRate'
        }
        /// <summary>
        /// Test the property 'LastExDividendDate'
        /// </summary>
        [Test]
        public void LastExDividendDateTest()
        {
            // TODO unit test for the property 'LastExDividendDate'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }

    }

}
