


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing EarningsDateEstimate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EarningsDateEstimateTests
    {
        // TODO uncomment below to declare an instance variable for EarningsDateEstimate
        //private EarningsDateEstimate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EarningsDateEstimate
            //instance = new EarningsDateEstimate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EarningsDateEstimate
        /// </summary>
        [Test]
        public void EarningsDateEstimateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EarningsDateEstimate
            //Assert.IsInstanceOfType<EarningsDateEstimate> (instance, "variable 'instance' is a EarningsDateEstimate");
        }


        /// <summary>
        /// Test the property 'FiscalYear'
        /// </summary>
        [Test]
        public void FiscalYearTest()
        {
            // TODO unit test for the property 'FiscalYear'
        }
        /// <summary>
        /// Test the property 'FiscalPeriod'
        /// </summary>
        [Test]
        public void FiscalPeriodTest()
        {
            // TODO unit test for the property 'FiscalPeriod'
        }
        /// <summary>
        /// Test the property 'ExpectedDate'
        /// </summary>
        [Test]
        public void ExpectedDateTest()
        {
            // TODO unit test for the property 'ExpectedDate'
        }
        /// <summary>
        /// Test the property 'Expected8kAt'
        /// </summary>
        [Test]
        public void Expected8kAtTest()
        {
            // TODO unit test for the property 'Expected8kAt'
        }
        /// <summary>
        /// Test the property 'HistoricallyEarliest'
        /// </summary>
        [Test]
        public void HistoricallyEarliestTest()
        {
            // TODO unit test for the property 'HistoricallyEarliest'
        }
        /// <summary>
        /// Test the property 'HistoricallyLatest'
        /// </summary>
        [Test]
        public void HistoricallyLatestTest()
        {
            // TODO unit test for the property 'HistoricallyLatest'
        }
        /// <summary>
        /// Test the property 'ConfidenceIntervals'
        /// </summary>
        [Test]
        public void ConfidenceIntervalsTest()
        {
            // TODO unit test for the property 'ConfidenceIntervals'
        }

    }

}
