


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ESGRating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ESGRatingTests
    {
        // TODO uncomment below to declare an instance variable for ESGRating
        //private ESGRating instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ESGRating
            //instance = new ESGRating();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ESGRating
        /// </summary>
        [Test]
        public void ESGRatingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ESGRating
            //Assert.IsInstanceOfType<ESGRating> (instance, "variable 'instance' is a ESGRating");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'CommunityRating'
        /// </summary>
        [Test]
        public void CommunityRatingTest()
        {
            // TODO unit test for the property 'CommunityRating'
        }
        /// <summary>
        /// Test the property 'EmployeeRating'
        /// </summary>
        [Test]
        public void EmployeeRatingTest()
        {
            // TODO unit test for the property 'EmployeeRating'
        }
        /// <summary>
        /// Test the property 'EnvironmentRating'
        /// </summary>
        [Test]
        public void EnvironmentRatingTest()
        {
            // TODO unit test for the property 'EnvironmentRating'
        }
        /// <summary>
        /// Test the property 'GovernanceRating'
        /// </summary>
        [Test]
        public void GovernanceRatingTest()
        {
            // TODO unit test for the property 'GovernanceRating'
        }

    }

}
