


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ETFHistoricalStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ETFHistoricalStatsTests
    {
        // TODO uncomment below to declare an instance variable for ETFHistoricalStats
        //private ETFHistoricalStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ETFHistoricalStats
            //instance = new ETFHistoricalStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ETFHistoricalStats
        /// </summary>
        [Test]
        public void ETFHistoricalStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ETFHistoricalStats
            //Assert.IsInstanceOfType<ETFHistoricalStats> (instance, "variable 'instance' is a ETFHistoricalStats");
        }


        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'Etf'
        /// </summary>
        [Test]
        public void EtfTest()
        {
            // TODO unit test for the property 'Etf'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
