


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ETFNavFlowsHistorical
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ETFNavFlowsHistoricalTests
    {
        // TODO uncomment below to declare an instance variable for ETFNavFlowsHistorical
        //private ETFNavFlowsHistorical instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ETFNavFlowsHistorical
            //instance = new ETFNavFlowsHistorical();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ETFNavFlowsHistorical
        /// </summary>
        [Test]
        public void ETFNavFlowsHistoricalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ETFNavFlowsHistorical
            //Assert.IsInstanceOfType<ETFNavFlowsHistorical> (instance, "variable 'instance' is a ETFNavFlowsHistorical");
        }


        /// <summary>
        /// Test the property 'NavFlows'
        /// </summary>
        [Test]
        public void NavFlowsTest()
        {
            // TODO unit test for the property 'NavFlows'
        }
        /// <summary>
        /// Test the property 'Etf'
        /// </summary>
        [Test]
        public void EtfTest()
        {
            // TODO unit test for the property 'Etf'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

    }

}
