


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ETFNavFlows
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ETFNavFlowsTests
    {
        // TODO uncomment below to declare an instance variable for ETFNavFlows
        //private ETFNavFlows instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ETFNavFlows
            //instance = new ETFNavFlows();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ETFNavFlows
        /// </summary>
        [Test]
        public void ETFNavFlowsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ETFNavFlows
            //Assert.IsInstanceOfType<ETFNavFlows> (instance, "variable 'instance' is a ETFNavFlows");
        }


        /// <summary>
        /// Test the property 'AsOfDate'
        /// </summary>
        [Test]
        public void AsOfDateTest()
        {
            // TODO unit test for the property 'AsOfDate'
        }
        /// <summary>
        /// Test the property 'NavReturnDaily'
        /// </summary>
        [Test]
        public void NavReturnDailyTest()
        {
            // TODO unit test for the property 'NavReturnDaily'
        }
        /// <summary>
        /// Test the property 'NavReturnOneMonth'
        /// </summary>
        [Test]
        public void NavReturnOneMonthTest()
        {
            // TODO unit test for the property 'NavReturnOneMonth'
        }
        /// <summary>
        /// Test the property 'NavReturnThreeMonth'
        /// </summary>
        [Test]
        public void NavReturnThreeMonthTest()
        {
            // TODO unit test for the property 'NavReturnThreeMonth'
        }
        /// <summary>
        /// Test the property 'NavReturnYtd'
        /// </summary>
        [Test]
        public void NavReturnYtdTest()
        {
            // TODO unit test for the property 'NavReturnYtd'
        }
        /// <summary>
        /// Test the property 'NavReturnOneYear'
        /// </summary>
        [Test]
        public void NavReturnOneYearTest()
        {
            // TODO unit test for the property 'NavReturnOneYear'
        }
        /// <summary>
        /// Test the property 'NavReturn1YearPrior'
        /// </summary>
        [Test]
        public void NavReturn1YearPriorTest()
        {
            // TODO unit test for the property 'NavReturn1YearPrior'
        }
        /// <summary>
        /// Test the property 'NavReturn2YearPrior'
        /// </summary>
        [Test]
        public void NavReturn2YearPriorTest()
        {
            // TODO unit test for the property 'NavReturn2YearPrior'
        }
        /// <summary>
        /// Test the property 'NavReturn3YearPrior'
        /// </summary>
        [Test]
        public void NavReturn3YearPriorTest()
        {
            // TODO unit test for the property 'NavReturn3YearPrior'
        }
        /// <summary>
        /// Test the property 'NavReturn4YearPrior'
        /// </summary>
        [Test]
        public void NavReturn4YearPriorTest()
        {
            // TODO unit test for the property 'NavReturn4YearPrior'
        }
        /// <summary>
        /// Test the property 'NavReturn5YearPrior'
        /// </summary>
        [Test]
        public void NavReturn5YearPriorTest()
        {
            // TODO unit test for the property 'NavReturn5YearPrior'
        }
        /// <summary>
        /// Test the property 'NavAnnualizedReturnThreeYear'
        /// </summary>
        [Test]
        public void NavAnnualizedReturnThreeYearTest()
        {
            // TODO unit test for the property 'NavAnnualizedReturnThreeYear'
        }
        /// <summary>
        /// Test the property 'NavAnnualizedReturnFiveYear'
        /// </summary>
        [Test]
        public void NavAnnualizedReturnFiveYearTest()
        {
            // TODO unit test for the property 'NavAnnualizedReturnFiveYear'
        }
        /// <summary>
        /// Test the property 'NavAnnualizedReturnTenYear'
        /// </summary>
        [Test]
        public void NavAnnualizedReturnTenYearTest()
        {
            // TODO unit test for the property 'NavAnnualizedReturnTenYear'
        }
        /// <summary>
        /// Test the property 'NavAnnualizedReturnInception'
        /// </summary>
        [Test]
        public void NavAnnualizedReturnInceptionTest()
        {
            // TODO unit test for the property 'NavAnnualizedReturnInception'
        }
        /// <summary>
        /// Test the property 'NavUnadjusted'
        /// </summary>
        [Test]
        public void NavUnadjustedTest()
        {
            // TODO unit test for the property 'NavUnadjusted'
        }
        /// <summary>
        /// Test the property 'NavSplitAdjusted'
        /// </summary>
        [Test]
        public void NavSplitAdjustedTest()
        {
            // TODO unit test for the property 'NavSplitAdjusted'
        }
        /// <summary>
        /// Test the property 'NavSplitDividendAdjusted'
        /// </summary>
        [Test]
        public void NavSplitDividendAdjustedTest()
        {
            // TODO unit test for the property 'NavSplitDividendAdjusted'
        }
        /// <summary>
        /// Test the property 'NetFlowsDaily'
        /// </summary>
        [Test]
        public void NetFlowsDailyTest()
        {
            // TODO unit test for the property 'NetFlowsDaily'
        }
        /// <summary>
        /// Test the property 'NetFlowsOneMonth'
        /// </summary>
        [Test]
        public void NetFlowsOneMonthTest()
        {
            // TODO unit test for the property 'NetFlowsOneMonth'
        }
        /// <summary>
        /// Test the property 'NetFlowsThreeMonth'
        /// </summary>
        [Test]
        public void NetFlowsThreeMonthTest()
        {
            // TODO unit test for the property 'NetFlowsThreeMonth'
        }
        /// <summary>
        /// Test the property 'NetFlowsYtd'
        /// </summary>
        [Test]
        public void NetFlowsYtdTest()
        {
            // TODO unit test for the property 'NetFlowsYtd'
        }
        /// <summary>
        /// Test the property 'NetFlowsOneYear'
        /// </summary>
        [Test]
        public void NetFlowsOneYearTest()
        {
            // TODO unit test for the property 'NetFlowsOneYear'
        }
        /// <summary>
        /// Test the property 'NetFlowsThreeYear'
        /// </summary>
        [Test]
        public void NetFlowsThreeYearTest()
        {
            // TODO unit test for the property 'NetFlowsThreeYear'
        }
        /// <summary>
        /// Test the property 'NetFlowsFiveYear'
        /// </summary>
        [Test]
        public void NetFlowsFiveYearTest()
        {
            // TODO unit test for the property 'NetFlowsFiveYear'
        }
        /// <summary>
        /// Test the property 'NetFlowsTenYear'
        /// </summary>
        [Test]
        public void NetFlowsTenYearTest()
        {
            // TODO unit test for the property 'NetFlowsTenYear'
        }
        /// <summary>
        /// Test the property 'NetFlows1YearPrior'
        /// </summary>
        [Test]
        public void NetFlows1YearPriorTest()
        {
            // TODO unit test for the property 'NetFlows1YearPrior'
        }
        /// <summary>
        /// Test the property 'NetFlows2YearPrior'
        /// </summary>
        [Test]
        public void NetFlows2YearPriorTest()
        {
            // TODO unit test for the property 'NetFlows2YearPrior'
        }
        /// <summary>
        /// Test the property 'NetFlows3YearPrior'
        /// </summary>
        [Test]
        public void NetFlows3YearPriorTest()
        {
            // TODO unit test for the property 'NetFlows3YearPrior'
        }
        /// <summary>
        /// Test the property 'NetFlows4YearPrior'
        /// </summary>
        [Test]
        public void NetFlows4YearPriorTest()
        {
            // TODO unit test for the property 'NetFlows4YearPrior'
        }
        /// <summary>
        /// Test the property 'NetFlows5YearPrior'
        /// </summary>
        [Test]
        public void NetFlows5YearPriorTest()
        {
            // TODO unit test for the property 'NetFlows5YearPrior'
        }
        /// <summary>
        /// Test the property 'NetFlowsInception'
        /// </summary>
        [Test]
        public void NetFlowsInceptionTest()
        {
            // TODO unit test for the property 'NetFlowsInception'
        }
        /// <summary>
        /// Test the property 'ShareOutstandingUnadjusted'
        /// </summary>
        [Test]
        public void ShareOutstandingUnadjustedTest()
        {
            // TODO unit test for the property 'ShareOutstandingUnadjusted'
        }
        /// <summary>
        /// Test the property 'ShareOutstandingSplitAdjusted'
        /// </summary>
        [Test]
        public void ShareOutstandingSplitAdjustedTest()
        {
            // TODO unit test for the property 'ShareOutstandingSplitAdjusted'
        }
        /// <summary>
        /// Test the property 'TotalNetAssets'
        /// </summary>
        [Test]
        public void TotalNetAssetsTest()
        {
            // TODO unit test for the property 'TotalNetAssets'
        }
        /// <summary>
        /// Test the property 'Etf'
        /// </summary>
        [Test]
        public void EtfTest()
        {
            // TODO unit test for the property 'Etf'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

    }

}
