


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ETFStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ETFStatsTests
    {
        // TODO uncomment below to declare an instance variable for ETFStats
        //private ETFStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ETFStats
            //instance = new ETFStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ETFStats
        /// </summary>
        [Test]
        public void ETFStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ETFStats
            //Assert.IsInstanceOfType<ETFStats> (instance, "variable 'instance' is a ETFStats");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'NetAssetValue'
        /// </summary>
        [Test]
        public void NetAssetValueTest()
        {
            // TODO unit test for the property 'NetAssetValue'
        }
        /// <summary>
        /// Test the property 'BetaVsSpy'
        /// </summary>
        [Test]
        public void BetaVsSpyTest()
        {
            // TODO unit test for the property 'BetaVsSpy'
        }
        /// <summary>
        /// Test the property 'TrailingOneMonthReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void TrailingOneMonthReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'TrailingOneMonthReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'TrailingOneMonthReturnSplitOnly'
        /// </summary>
        [Test]
        public void TrailingOneMonthReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'TrailingOneMonthReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'TrailingOneYearReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void TrailingOneYearReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'TrailingOneYearReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'TrailingOneYearReturnSplitOnly'
        /// </summary>
        [Test]
        public void TrailingOneYearReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'TrailingOneYearReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'TrailingOneYearVolatilityAnnualized'
        /// </summary>
        [Test]
        public void TrailingOneYearVolatilityAnnualizedTest()
        {
            // TODO unit test for the property 'TrailingOneYearVolatilityAnnualized'
        }
        /// <summary>
        /// Test the property 'TrailingThreeYearAnnualizedReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void TrailingThreeYearAnnualizedReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'TrailingThreeYearAnnualizedReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'TrailingThreeYearAnnualizedReturnSplitOnly'
        /// </summary>
        [Test]
        public void TrailingThreeYearAnnualizedReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'TrailingThreeYearAnnualizedReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'TrailingThreeYearVolatilityAnnualized'
        /// </summary>
        [Test]
        public void TrailingThreeYearVolatilityAnnualizedTest()
        {
            // TODO unit test for the property 'TrailingThreeYearVolatilityAnnualized'
        }
        /// <summary>
        /// Test the property 'TrailingFiveYearAnnualizedReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void TrailingFiveYearAnnualizedReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'TrailingFiveYearAnnualizedReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'TrailingFiveYearAnnualizedReturnSplitOnly'
        /// </summary>
        [Test]
        public void TrailingFiveYearAnnualizedReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'TrailingFiveYearAnnualizedReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'TrailingFiveYearVolatilityAnnualized'
        /// </summary>
        [Test]
        public void TrailingFiveYearVolatilityAnnualizedTest()
        {
            // TODO unit test for the property 'TrailingFiveYearVolatilityAnnualized'
        }
        /// <summary>
        /// Test the property 'TrailingTenYearAnnualizedReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void TrailingTenYearAnnualizedReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'TrailingTenYearAnnualizedReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'TrailingTenYearAnnualizedReturnSplitOnly'
        /// </summary>
        [Test]
        public void TrailingTenYearAnnualizedReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'TrailingTenYearAnnualizedReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'InceptionAnnualizedReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void InceptionAnnualizedReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'InceptionAnnualizedReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'InceptionAnnualizedReturnSplitOnly'
        /// </summary>
        [Test]
        public void InceptionAnnualizedReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'InceptionAnnualizedReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYear5ReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYear5ReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYear5ReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYear5ReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYear5ReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYear5ReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYear4ReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYear4ReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYear4ReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYear4ReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYear4ReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYear4ReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYear3ReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYear3ReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYear3ReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYear3ReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYear3ReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYear3ReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYear2ReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYear2ReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYear2ReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYear2ReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYear2ReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYear2ReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYear1ReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYear1ReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYear1ReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYear1ReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYear1ReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYear1ReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'CalendarYearToDateReturnSplitAndDividend'
        /// </summary>
        [Test]
        public void CalendarYearToDateReturnSplitAndDividendTest()
        {
            // TODO unit test for the property 'CalendarYearToDateReturnSplitAndDividend'
        }
        /// <summary>
        /// Test the property 'CalendarYearToDateReturnSplitOnly'
        /// </summary>
        [Test]
        public void CalendarYearToDateReturnSplitOnlyTest()
        {
            // TODO unit test for the property 'CalendarYearToDateReturnSplitOnly'
        }
        /// <summary>
        /// Test the property 'Etf'
        /// </summary>
        [Test]
        public void EtfTest()
        {
            // TODO unit test for the property 'Etf'
        }

    }

}
