


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing FilingNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilingNoteTests
    {
        // TODO uncomment below to declare an instance variable for FilingNote
        //private FilingNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilingNote
            //instance = new FilingNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilingNote
        /// </summary>
        [Test]
        public void FilingNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilingNote
            //Assert.IsInstanceOfType<FilingNote> (instance, "variable 'instance' is a FilingNote");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'XbrlTag'
        /// </summary>
        [Test]
        public void XbrlTagTest()
        {
            // TODO unit test for the property 'XbrlTag'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Filing'
        /// </summary>
        [Test]
        public void FilingTest()
        {
            // TODO unit test for the property 'Filing'
        }

    }

}
