


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ForexPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForexPriceTests
    {
        // TODO uncomment below to declare an instance variable for ForexPrice
        //private ForexPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForexPrice
            //instance = new ForexPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForexPrice
        /// </summary>
        [Test]
        public void ForexPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForexPrice
            //Assert.IsInstanceOfType<ForexPrice> (instance, "variable 'instance' is a ForexPrice");
        }


        /// <summary>
        /// Test the property 'OccurredAt'
        /// </summary>
        [Test]
        public void OccurredAtTest()
        {
            // TODO unit test for the property 'OccurredAt'
        }
        /// <summary>
        /// Test the property 'OpenBid'
        /// </summary>
        [Test]
        public void OpenBidTest()
        {
            // TODO unit test for the property 'OpenBid'
        }
        /// <summary>
        /// Test the property 'HighBid'
        /// </summary>
        [Test]
        public void HighBidTest()
        {
            // TODO unit test for the property 'HighBid'
        }
        /// <summary>
        /// Test the property 'LowBid'
        /// </summary>
        [Test]
        public void LowBidTest()
        {
            // TODO unit test for the property 'LowBid'
        }
        /// <summary>
        /// Test the property 'CloseBid'
        /// </summary>
        [Test]
        public void CloseBidTest()
        {
            // TODO unit test for the property 'CloseBid'
        }
        /// <summary>
        /// Test the property 'OpenAsk'
        /// </summary>
        [Test]
        public void OpenAskTest()
        {
            // TODO unit test for the property 'OpenAsk'
        }
        /// <summary>
        /// Test the property 'HighAsk'
        /// </summary>
        [Test]
        public void HighAskTest()
        {
            // TODO unit test for the property 'HighAsk'
        }
        /// <summary>
        /// Test the property 'LowAsk'
        /// </summary>
        [Test]
        public void LowAskTest()
        {
            // TODO unit test for the property 'LowAsk'
        }
        /// <summary>
        /// Test the property 'CloseAsk'
        /// </summary>
        [Test]
        public void CloseAskTest()
        {
            // TODO unit test for the property 'CloseAsk'
        }
        /// <summary>
        /// Test the property 'TotalTicks'
        /// </summary>
        [Test]
        public void TotalTicksTest()
        {
            // TODO unit test for the property 'TotalTicks'
        }

    }

}
