


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing Fundamental
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FundamentalTests
    {
        // TODO uncomment below to declare an instance variable for Fundamental
        //private Fundamental instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Fundamental
            //instance = new Fundamental();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Fundamental
        /// </summary>
        [Test]
        public void FundamentalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Fundamental
            //Assert.IsInstanceOfType<Fundamental> (instance, "variable 'instance' is a Fundamental");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StatementCode'
        /// </summary>
        [Test]
        public void StatementCodeTest()
        {
            // TODO unit test for the property 'StatementCode'
        }
        /// <summary>
        /// Test the property 'FiscalYear'
        /// </summary>
        [Test]
        public void FiscalYearTest()
        {
            // TODO unit test for the property 'FiscalYear'
        }
        /// <summary>
        /// Test the property 'FiscalPeriod'
        /// </summary>
        [Test]
        public void FiscalPeriodTest()
        {
            // TODO unit test for the property 'FiscalPeriod'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'FilingDate'
        /// </summary>
        [Test]
        public void FilingDateTest()
        {
            // TODO unit test for the property 'FilingDate'
        }
        /// <summary>
        /// Test the property 'IsLatest'
        /// </summary>
        [Test]
        public void IsLatestTest()
        {
            // TODO unit test for the property 'IsLatest'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

    }

}
