


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing InstitutionalHolding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InstitutionalHoldingTests
    {
        // TODO uncomment below to declare an instance variable for InstitutionalHolding
        //private InstitutionalHolding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstitutionalHolding
            //instance = new InstitutionalHolding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstitutionalHolding
        /// </summary>
        [Test]
        public void InstitutionalHoldingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstitutionalHolding
            //Assert.IsInstanceOfType<InstitutionalHolding> (instance, "variable 'instance' is a InstitutionalHolding");
        }


        /// <summary>
        /// Test the property 'Cusip'
        /// </summary>
        [Test]
        public void CusipTest()
        {
            // TODO unit test for the property 'Cusip'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'SecurityName'
        /// </summary>
        [Test]
        public void SecurityNameTest()
        {
            // TODO unit test for the property 'SecurityName'
        }
        /// <summary>
        /// Test the property 'SecurityType'
        /// </summary>
        [Test]
        public void SecurityTypeTest()
        {
            // TODO unit test for the property 'SecurityType'
        }
        /// <summary>
        /// Test the property 'TitleOfClass'
        /// </summary>
        [Test]
        public void TitleOfClassTest()
        {
            // TODO unit test for the property 'TitleOfClass'
        }
        /// <summary>
        /// Test the property 'StockExchange'
        /// </summary>
        [Test]
        public void StockExchangeTest()
        {
            // TODO unit test for the property 'StockExchange'
        }
        /// <summary>
        /// Test the property 'FilingDate'
        /// </summary>
        [Test]
        public void FilingDateTest()
        {
            // TODO unit test for the property 'FilingDate'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'InvestmentDiscretion'
        /// </summary>
        [Test]
        public void InvestmentDiscretionTest()
        {
            // TODO unit test for the property 'InvestmentDiscretion'
        }
        /// <summary>
        /// Test the property 'OtherManager'
        /// </summary>
        [Test]
        public void OtherManagerTest()
        {
            // TODO unit test for the property 'OtherManager'
        }
        /// <summary>
        /// Test the property 'SoleVotingAuthority'
        /// </summary>
        [Test]
        public void SoleVotingAuthorityTest()
        {
            // TODO unit test for the property 'SoleVotingAuthority'
        }
        /// <summary>
        /// Test the property 'SharedVotingAuthority'
        /// </summary>
        [Test]
        public void SharedVotingAuthorityTest()
        {
            // TODO unit test for the property 'SharedVotingAuthority'
        }
        /// <summary>
        /// Test the property 'NoVotingAuthority'
        /// </summary>
        [Test]
        public void NoVotingAuthorityTest()
        {
            // TODO unit test for the property 'NoVotingAuthority'
        }

    }

}
