


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing MarketStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketStatusResultTests
    {
        // TODO uncomment below to declare an instance variable for MarketStatusResult
        //private MarketStatusResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketStatusResult
            //instance = new MarketStatusResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketStatusResult
        /// </summary>
        [Test]
        public void MarketStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketStatusResult
            //Assert.IsInstanceOfType<MarketStatusResult> (instance, "variable 'instance' is a MarketStatusResult");
        }


        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'IsOpen'
        /// </summary>
        [Test]
        public void IsOpenTest()
        {
            // TODO unit test for the property 'IsOpen'
        }

    }

}
