


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing Municipality
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MunicipalityTests
    {
        // TODO uncomment below to declare an instance variable for Municipality
        //private Municipality instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Municipality
            //instance = new Municipality();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Municipality
        /// </summary>
        [Test]
        public void MunicipalityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Municipality
            //Assert.IsInstanceOfType<Municipality> (instance, "variable 'instance' is a Municipality");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CensusId'
        /// </summary>
        [Test]
        public void CensusIdTest()
        {
            // TODO unit test for the property 'CensusId'
        }
        /// <summary>
        /// Test the property 'GovernmentName'
        /// </summary>
        [Test]
        public void GovernmentNameTest()
        {
            // TODO unit test for the property 'GovernmentName'
        }
        /// <summary>
        /// Test the property 'GovernmentType'
        /// </summary>
        [Test]
        public void GovernmentTypeTest()
        {
            // TODO unit test for the property 'GovernmentType'
        }
        /// <summary>
        /// Test the property 'PrimaryContactType'
        /// </summary>
        [Test]
        public void PrimaryContactTypeTest()
        {
            // TODO unit test for the property 'PrimaryContactType'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'WebSite'
        /// </summary>
        [Test]
        public void WebSiteTest()
        {
            // TODO unit test for the property 'WebSite'
        }
        /// <summary>
        /// Test the property 'Population'
        /// </summary>
        [Test]
        public void PopulationTest()
        {
            // TODO unit test for the property 'Population'
        }
        /// <summary>
        /// Test the property 'PopulationAsOfYear'
        /// </summary>
        [Test]
        public void PopulationAsOfYearTest()
        {
            // TODO unit test for the property 'PopulationAsOfYear'
        }
        /// <summary>
        /// Test the property 'Enrollment'
        /// </summary>
        [Test]
        public void EnrollmentTest()
        {
            // TODO unit test for the property 'Enrollment'
        }
        /// <summary>
        /// Test the property 'EnrollmentAsOfYear'
        /// </summary>
        [Test]
        public void EnrollmentAsOfYearTest()
        {
            // TODO unit test for the property 'EnrollmentAsOfYear'
        }
        /// <summary>
        /// Test the property 'AreaName'
        /// </summary>
        [Test]
        public void AreaNameTest()
        {
            // TODO unit test for the property 'AreaName'
        }
        /// <summary>
        /// Test the property 'AreaType'
        /// </summary>
        [Test]
        public void AreaTypeTest()
        {
            // TODO unit test for the property 'AreaType'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
