


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing NegativeVolumeIndexTechnicalValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NegativeVolumeIndexTechnicalValueTests
    {
        // TODO uncomment below to declare an instance variable for NegativeVolumeIndexTechnicalValue
        //private NegativeVolumeIndexTechnicalValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NegativeVolumeIndexTechnicalValue
            //instance = new NegativeVolumeIndexTechnicalValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NegativeVolumeIndexTechnicalValue
        /// </summary>
        [Test]
        public void NegativeVolumeIndexTechnicalValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NegativeVolumeIndexTechnicalValue
            //Assert.IsInstanceOfType<NegativeVolumeIndexTechnicalValue> (instance, "variable 'instance' is a NegativeVolumeIndexTechnicalValue");
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Nvi'
        /// </summary>
        [Test]
        public void NviTest()
        {
            // TODO unit test for the property 'Nvi'
        }

    }

}
