


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionRealtime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionRealtimeTests
    {
        // TODO uncomment below to declare an instance variable for OptionRealtime
        //private OptionRealtime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionRealtime
            //instance = new OptionRealtime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionRealtime
        /// </summary>
        [Test]
        public void OptionRealtimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionRealtime
            //Assert.IsInstanceOfType<OptionRealtime> (instance, "variable 'instance' is a OptionRealtime");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
        /// <summary>
        /// Test the property 'Strike'
        /// </summary>
        [Test]
        public void StrikeTest()
        {
            // TODO unit test for the property 'Strike'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
