


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionUnusualTrade
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionUnusualTradeTests
    {
        // TODO uncomment below to declare an instance variable for OptionUnusualTrade
        //private OptionUnusualTrade instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionUnusualTrade
            //instance = new OptionUnusualTrade();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionUnusualTrade
        /// </summary>
        [Test]
        public void OptionUnusualTradeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionUnusualTrade
            //Assert.IsInstanceOfType<OptionUnusualTrade> (instance, "variable 'instance' is a OptionUnusualTrade");
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TotalValue'
        /// </summary>
        [Test]
        public void TotalValueTest()
        {
            // TODO unit test for the property 'TotalValue'
        }
        /// <summary>
        /// Test the property 'ContractType'
        /// </summary>
        [Test]
        public void ContractTypeTest()
        {
            // TODO unit test for the property 'ContractType'
        }
        /// <summary>
        /// Test the property 'ContractExpiration'
        /// </summary>
        [Test]
        public void ContractExpirationTest()
        {
            // TODO unit test for the property 'ContractExpiration'
        }
        /// <summary>
        /// Test the property 'ContractStrike'
        /// </summary>
        [Test]
        public void ContractStrikeTest()
        {
            // TODO unit test for the property 'ContractStrike'
        }

    }

}
