


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionStatsRealtime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionStatsRealtimeTests
    {
        // TODO uncomment below to declare an instance variable for OptionStatsRealtime
        //private OptionStatsRealtime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionStatsRealtime
            //instance = new OptionStatsRealtime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionStatsRealtime
        /// </summary>
        [Test]
        public void OptionStatsRealtimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionStatsRealtime
            //Assert.IsInstanceOfType<OptionStatsRealtime> (instance, "variable 'instance' is a OptionStatsRealtime");
        }


        /// <summary>
        /// Test the property 'ImpliedVolatility'
        /// </summary>
        [Test]
        public void ImpliedVolatilityTest()
        {
            // TODO unit test for the property 'ImpliedVolatility'
        }
        /// <summary>
        /// Test the property 'Delta'
        /// </summary>
        [Test]
        public void DeltaTest()
        {
            // TODO unit test for the property 'Delta'
        }
        /// <summary>
        /// Test the property 'Gamma'
        /// </summary>
        [Test]
        public void GammaTest()
        {
            // TODO unit test for the property 'Gamma'
        }
        /// <summary>
        /// Test the property 'Theta'
        /// </summary>
        [Test]
        public void ThetaTest()
        {
            // TODO unit test for the property 'Theta'
        }
        /// <summary>
        /// Test the property 'Vega'
        /// </summary>
        [Test]
        public void VegaTest()
        {
            // TODO unit test for the property 'Vega'
        }
        /// <summary>
        /// Test the property 'UnderlyingPrice'
        /// </summary>
        [Test]
        public void UnderlyingPriceTest()
        {
            // TODO unit test for the property 'UnderlyingPrice'
        }

    }

}
