


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionIntervalsMoversResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionIntervalsMoversResultTests
    {
        // TODO uncomment below to declare an instance variable for OptionIntervalsMoversResult
        //private OptionIntervalsMoversResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionIntervalsMoversResult
            //instance = new OptionIntervalsMoversResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionIntervalsMoversResult
        /// </summary>
        [Test]
        public void OptionIntervalsMoversResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionIntervalsMoversResult
            //Assert.IsInstanceOfType<OptionIntervalsMoversResult> (instance, "variable 'instance' is a OptionIntervalsMoversResult");
        }


        /// <summary>
        /// Test the property 'OpenTime'
        /// </summary>
        [Test]
        public void OpenTimeTest()
        {
            // TODO unit test for the property 'OpenTime'
        }
        /// <summary>
        /// Test the property 'CloseTime'
        /// </summary>
        [Test]
        public void CloseTimeTest()
        {
            // TODO unit test for the property 'CloseTime'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Intervals'
        /// </summary>
        [Test]
        public void IntervalsTest()
        {
            // TODO unit test for the property 'Intervals'
        }

    }

}
