


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionTrades
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionTradesTests
    {
        // TODO uncomment below to declare an instance variable for OptionTrades
        //private OptionTrades instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionTrades
            //instance = new OptionTrades();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionTrades
        /// </summary>
        [Test]
        public void OptionTradesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionTrades
            //Assert.IsInstanceOfType<OptionTrades> (instance, "variable 'instance' is a OptionTrades");
        }


        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [Test]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'UnderlyingSymbol'
        /// </summary>
        [Test]
        public void UnderlyingSymbolTest()
        {
            // TODO unit test for the property 'UnderlyingSymbol'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'TotalVolume'
        /// </summary>
        [Test]
        public void TotalVolumeTest()
        {
            // TODO unit test for the property 'TotalVolume'
        }
        /// <summary>
        /// Test the property 'AskPriceAtExecution'
        /// </summary>
        [Test]
        public void AskPriceAtExecutionTest()
        {
            // TODO unit test for the property 'AskPriceAtExecution'
        }
        /// <summary>
        /// Test the property 'BidPriceAtExecution'
        /// </summary>
        [Test]
        public void BidPriceAtExecutionTest()
        {
            // TODO unit test for the property 'BidPriceAtExecution'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'SequenceId'
        /// </summary>
        [Test]
        public void SequenceIdTest()
        {
            // TODO unit test for the property 'SequenceId'
        }

    }

}
