


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing OptionsAggregate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionsAggregateTests
    {
        // TODO uncomment below to declare an instance variable for OptionsAggregate
        //private OptionsAggregate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptionsAggregate
            //instance = new OptionsAggregate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptionsAggregate
        /// </summary>
        [Test]
        public void OptionsAggregateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptionsAggregate
            //Assert.IsInstanceOfType<OptionsAggregate> (instance, "variable 'instance' is a OptionsAggregate");
        }


        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'TotalOpenInterest'
        /// </summary>
        [Test]
        public void TotalOpenInterestTest()
        {
            // TODO unit test for the property 'TotalOpenInterest'
        }
        /// <summary>
        /// Test the property 'TotalVolume'
        /// </summary>
        [Test]
        public void TotalVolumeTest()
        {
            // TODO unit test for the property 'TotalVolume'
        }

    }

}
