


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing RelativeStrengthIndexTechnicalValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelativeStrengthIndexTechnicalValueTests
    {
        // TODO uncomment below to declare an instance variable for RelativeStrengthIndexTechnicalValue
        //private RelativeStrengthIndexTechnicalValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelativeStrengthIndexTechnicalValue
            //instance = new RelativeStrengthIndexTechnicalValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelativeStrengthIndexTechnicalValue
        /// </summary>
        [Test]
        public void RelativeStrengthIndexTechnicalValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelativeStrengthIndexTechnicalValue
            //Assert.IsInstanceOfType<RelativeStrengthIndexTechnicalValue> (instance, "variable 'instance' is a RelativeStrengthIndexTechnicalValue");
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Rsi'
        /// </summary>
        [Test]
        public void RsiTest()
        {
            // TODO unit test for the property 'Rsi'
        }

    }

}
