


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ReportedFinancial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportedFinancialTests
    {
        // TODO uncomment below to declare an instance variable for ReportedFinancial
        //private ReportedFinancial instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportedFinancial
            //instance = new ReportedFinancial();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportedFinancial
        /// </summary>
        [Test]
        public void ReportedFinancialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportedFinancial
            //Assert.IsInstanceOfType<ReportedFinancial> (instance, "variable 'instance' is a ReportedFinancial");
        }


        /// <summary>
        /// Test the property 'XbrlTag'
        /// </summary>
        [Test]
        public void XbrlTagTest()
        {
            // TODO unit test for the property 'XbrlTag'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
