


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing SecurityTrades
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityTradesTests
    {
        // TODO uncomment below to declare an instance variable for SecurityTrades
        //private SecurityTrades instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecurityTrades
            //instance = new SecurityTrades();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecurityTrades
        /// </summary>
        [Test]
        public void SecurityTradesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecurityTrades
            //Assert.IsInstanceOfType<SecurityTrades> (instance, "variable 'instance' is a SecurityTrades");
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'TotalVolume'
        /// </summary>
        [Test]
        public void TotalVolumeTest()
        {
            // TODO unit test for the property 'TotalVolume'
        }
        /// <summary>
        /// Test the property 'MarketCenter'
        /// </summary>
        [Test]
        public void MarketCenterTest()
        {
            // TODO unit test for the property 'MarketCenter'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property 'IsDarkpool'
        /// </summary>
        [Test]
        public void IsDarkpoolTest()
        {
            // TODO unit test for the property 'IsDarkpool'
        }

    }

}
