


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing SecuritySnapshotsResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecuritySnapshotsResultTests
    {
        // TODO uncomment below to declare an instance variable for SecuritySnapshotsResult
        //private SecuritySnapshotsResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecuritySnapshotsResult
            //instance = new SecuritySnapshotsResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecuritySnapshotsResult
        /// </summary>
        [Test]
        public void SecuritySnapshotsResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecuritySnapshotsResult
            //Assert.IsInstanceOfType<SecuritySnapshotsResult> (instance, "variable 'instance' is a SecuritySnapshotsResult");
        }


        /// <summary>
        /// Test the property 'Snapshots'
        /// </summary>
        [Test]
        public void SnapshotsTest()
        {
            // TODO unit test for the property 'Snapshots'
        }

    }

}
