


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing SecurityTradingStatusSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityTradingStatusSummaryTests
    {
        // TODO uncomment below to declare an instance variable for SecurityTradingStatusSummary
        //private SecurityTradingStatusSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecurityTradingStatusSummary
            //instance = new SecurityTradingStatusSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecurityTradingStatusSummary
        /// </summary>
        [Test]
        public void SecurityTradingStatusSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecurityTradingStatusSummary
            //Assert.IsInstanceOfType<SecurityTradingStatusSummary> (instance, "variable 'instance' is a SecurityTradingStatusSummary");
        }


        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'TradingStatus'
        /// </summary>
        [Test]
        public void TradingStatusTest()
        {
            // TODO unit test for the property 'TradingStatus'
        }
        /// <summary>
        /// Test the property 'TradingStatusReason'
        /// </summary>
        [Test]
        public void TradingStatusReasonTest()
        {
            // TODO unit test for the property 'TradingStatusReason'
        }
        /// <summary>
        /// Test the property 'TradingStatusUpdatedOn'
        /// </summary>
        [Test]
        public void TradingStatusUpdatedOnTest()
        {
            // TODO unit test for the property 'TradingStatusUpdatedOn'
        }

    }

}
