


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing SecuritySnapshotGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecuritySnapshotGroupTests
    {
        // TODO uncomment below to declare an instance variable for SecuritySnapshotGroup
        //private SecuritySnapshotGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecuritySnapshotGroup
            //instance = new SecuritySnapshotGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecuritySnapshotGroup
        /// </summary>
        [Test]
        public void SecuritySnapshotGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecuritySnapshotGroup
            //Assert.IsInstanceOfType<SecuritySnapshotGroup> (instance, "variable 'instance' is a SecuritySnapshotGroup");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Test]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

    }

}
