


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ShortInterest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShortInterestTests
    {
        // TODO uncomment below to declare an instance variable for ShortInterest
        //private ShortInterest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShortInterest
            //instance = new ShortInterest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShortInterest
        /// </summary>
        [Test]
        public void ShortInterestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShortInterest
            //Assert.IsInstanceOfType<ShortInterest> (instance, "variable 'instance' is a ShortInterest");
        }


        /// <summary>
        /// Test the property 'SettlementDate'
        /// </summary>
        [Test]
        public void SettlementDateTest()
        {
            // TODO unit test for the property 'SettlementDate'
        }
        /// <summary>
        /// Test the property 'CurrentShortPosition'
        /// </summary>
        [Test]
        public void CurrentShortPositionTest()
        {
            // TODO unit test for the property 'CurrentShortPosition'
        }
        /// <summary>
        /// Test the property 'PreviousShortPosition'
        /// </summary>
        [Test]
        public void PreviousShortPositionTest()
        {
            // TODO unit test for the property 'PreviousShortPosition'
        }
        /// <summary>
        /// Test the property 'ChangePercent'
        /// </summary>
        [Test]
        public void ChangePercentTest()
        {
            // TODO unit test for the property 'ChangePercent'
        }
        /// <summary>
        /// Test the property 'DaysToCover'
        /// </summary>
        [Test]
        public void DaysToCoverTest()
        {
            // TODO unit test for the property 'DaysToCover'
        }
        /// <summary>
        /// Test the property 'AverageDailyVolume'
        /// </summary>
        [Test]
        public void AverageDailyVolumeTest()
        {
            // TODO unit test for the property 'AverageDailyVolume'
        }

    }

}
