


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing StandardizedFinancial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StandardizedFinancialTests
    {
        // TODO uncomment below to declare an instance variable for StandardizedFinancial
        //private StandardizedFinancial instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StandardizedFinancial
            //instance = new StandardizedFinancial();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StandardizedFinancial
        /// </summary>
        [Test]
        public void StandardizedFinancialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StandardizedFinancial
            //Assert.IsInstanceOfType<StandardizedFinancial> (instance, "variable 'instance' is a StandardizedFinancial");
        }


        /// <summary>
        /// Test the property 'DataTag'
        /// </summary>
        [Test]
        public void DataTagTest()
        {
            // TODO unit test for the property 'DataTag'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
