


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing StockPriceAdjustment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StockPriceAdjustmentTests
    {
        // TODO uncomment below to declare an instance variable for StockPriceAdjustment
        //private StockPriceAdjustment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StockPriceAdjustment
            //instance = new StockPriceAdjustment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StockPriceAdjustment
        /// </summary>
        [Test]
        public void StockPriceAdjustmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StockPriceAdjustment
            //Assert.IsInstanceOfType<StockPriceAdjustment> (instance, "variable 'instance' is a StockPriceAdjustment");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Factor'
        /// </summary>
        [Test]
        public void FactorTest()
        {
            // TODO unit test for the property 'Factor'
        }
        /// <summary>
        /// Test the property 'Dividend'
        /// </summary>
        [Test]
        public void DividendTest()
        {
            // TODO unit test for the property 'Dividend'
        }
        /// <summary>
        /// Test the property 'DividendCurrency'
        /// </summary>
        [Test]
        public void DividendCurrencyTest()
        {
            // TODO unit test for the property 'DividendCurrency'
        }
        /// <summary>
        /// Test the property 'SplitRatio'
        /// </summary>
        [Test]
        public void SplitRatioTest()
        {
            // TODO unit test for the property 'SplitRatio'
        }

    }

}
