


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing StockPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StockPriceTests
    {
        // TODO uncomment below to declare an instance variable for StockPrice
        //private StockPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StockPrice
            //instance = new StockPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StockPrice
        /// </summary>
        [Test]
        public void StockPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StockPrice
            //Assert.IsInstanceOfType<StockPrice> (instance, "variable 'instance' is a StockPrice");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Intraperiod'
        /// </summary>
        [Test]
        public void IntraperiodTest()
        {
            // TODO unit test for the property 'Intraperiod'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Test]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Test]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Test]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Test]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'AdjOpen'
        /// </summary>
        [Test]
        public void AdjOpenTest()
        {
            // TODO unit test for the property 'AdjOpen'
        }
        /// <summary>
        /// Test the property 'AdjHigh'
        /// </summary>
        [Test]
        public void AdjHighTest()
        {
            // TODO unit test for the property 'AdjHigh'
        }
        /// <summary>
        /// Test the property 'AdjLow'
        /// </summary>
        [Test]
        public void AdjLowTest()
        {
            // TODO unit test for the property 'AdjLow'
        }
        /// <summary>
        /// Test the property 'AdjClose'
        /// </summary>
        [Test]
        public void AdjCloseTest()
        {
            // TODO unit test for the property 'AdjClose'
        }
        /// <summary>
        /// Test the property 'AdjVolume'
        /// </summary>
        [Test]
        public void AdjVolumeTest()
        {
            // TODO unit test for the property 'AdjVolume'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }

    }

}
