


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing VolumePriceTrendTechnicalValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VolumePriceTrendTechnicalValueTests
    {
        // TODO uncomment below to declare an instance variable for VolumePriceTrendTechnicalValue
        //private VolumePriceTrendTechnicalValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VolumePriceTrendTechnicalValue
            //instance = new VolumePriceTrendTechnicalValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VolumePriceTrendTechnicalValue
        /// </summary>
        [Test]
        public void VolumePriceTrendTechnicalValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VolumePriceTrendTechnicalValue
            //Assert.IsInstanceOfType<VolumePriceTrendTechnicalValue> (instance, "variable 'instance' is a VolumePriceTrendTechnicalValue");
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Vpt'
        /// </summary>
        [Test]
        public void VptTest()
        {
            // TODO unit test for the property 'Vpt'
        }

    }

}
