


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksAnalystRatingSnapshot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksAnalystRatingSnapshotTests
    {
        // TODO uncomment below to declare an instance variable for ZacksAnalystRatingSnapshot
        //private ZacksAnalystRatingSnapshot instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksAnalystRatingSnapshot
            //instance = new ZacksAnalystRatingSnapshot();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksAnalystRatingSnapshot
        /// </summary>
        [Test]
        public void ZacksAnalystRatingSnapshotInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksAnalystRatingSnapshot
            //Assert.IsInstanceOfType<ZacksAnalystRatingSnapshot> (instance, "variable 'instance' is a ZacksAnalystRatingSnapshot");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SnapshotDate'
        /// </summary>
        [Test]
        public void SnapshotDateTest()
        {
            // TODO unit test for the property 'SnapshotDate'
        }
        /// <summary>
        /// Test the property 'RatingDate'
        /// </summary>
        [Test]
        public void RatingDateTest()
        {
            // TODO unit test for the property 'RatingDate'
        }
        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Test]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }
        /// <summary>
        /// Test the property 'Percentile'
        /// </summary>
        [Test]
        public void PercentileTest()
        {
            // TODO unit test for the property 'Percentile'
        }
        /// <summary>
        /// Test the property 'StrongBuys'
        /// </summary>
        [Test]
        public void StrongBuysTest()
        {
            // TODO unit test for the property 'StrongBuys'
        }
        /// <summary>
        /// Test the property 'Buys'
        /// </summary>
        [Test]
        public void BuysTest()
        {
            // TODO unit test for the property 'Buys'
        }
        /// <summary>
        /// Test the property 'Holds'
        /// </summary>
        [Test]
        public void HoldsTest()
        {
            // TODO unit test for the property 'Holds'
        }
        /// <summary>
        /// Test the property 'Sells'
        /// </summary>
        [Test]
        public void SellsTest()
        {
            // TODO unit test for the property 'Sells'
        }
        /// <summary>
        /// Test the property 'StrongSells'
        /// </summary>
        [Test]
        public void StrongSellsTest()
        {
            // TODO unit test for the property 'StrongSells'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
