


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksInstitutionalHolding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksInstitutionalHoldingTests
    {
        // TODO uncomment below to declare an instance variable for ZacksInstitutionalHolding
        //private ZacksInstitutionalHolding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksInstitutionalHolding
            //instance = new ZacksInstitutionalHolding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksInstitutionalHolding
        /// </summary>
        [Test]
        public void ZacksInstitutionalHoldingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksInstitutionalHolding
            //Assert.IsInstanceOfType<ZacksInstitutionalHolding> (instance, "variable 'instance' is a ZacksInstitutionalHolding");
        }


        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'AsOfDate'
        /// </summary>
        [Test]
        public void AsOfDateTest()
        {
            // TODO unit test for the property 'AsOfDate'
        }
        /// <summary>
        /// Test the property 'SharesHeld'
        /// </summary>
        [Test]
        public void SharesHeldTest()
        {
            // TODO unit test for the property 'SharesHeld'
        }
        /// <summary>
        /// Test the property 'SharedHeldPercent'
        /// </summary>
        [Test]
        public void SharedHeldPercentTest()
        {
            // TODO unit test for the property 'SharedHeldPercent'
        }
        /// <summary>
        /// Test the property 'SharesChange'
        /// </summary>
        [Test]
        public void SharesChangeTest()
        {
            // TODO unit test for the property 'SharesChange'
        }
        /// <summary>
        /// Test the property 'SharesChangePercent'
        /// </summary>
        [Test]
        public void SharesChangePercentTest()
        {
            // TODO unit test for the property 'SharesChangePercent'
        }
        /// <summary>
        /// Test the property 'MarketValue'
        /// </summary>
        [Test]
        public void MarketValueTest()
        {
            // TODO unit test for the property 'MarketValue'
        }
        /// <summary>
        /// Test the property 'MarketValueChange'
        /// </summary>
        [Test]
        public void MarketValueChangeTest()
        {
            // TODO unit test for the property 'MarketValueChange'
        }
        /// <summary>
        /// Test the property 'LastSecFilingType'
        /// </summary>
        [Test]
        public void LastSecFilingTypeTest()
        {
            // TODO unit test for the property 'LastSecFilingType'
        }
        /// <summary>
        /// Test the property 'LastSecFilingDate'
        /// </summary>
        [Test]
        public void LastSecFilingDateTest()
        {
            // TODO unit test for the property 'LastSecFilingDate'
        }
        /// <summary>
        /// Test the property 'LastSecFilingShares'
        /// </summary>
        [Test]
        public void LastSecFilingSharesTest()
        {
            // TODO unit test for the property 'LastSecFilingShares'
        }
        /// <summary>
        /// Test the property 'HistoricalHoldings'
        /// </summary>
        [Test]
        public void HistoricalHoldingsTest()
        {
            // TODO unit test for the property 'HistoricalHoldings'
        }

    }

}
