


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksTargetPriceConsensus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksTargetPriceConsensusTests
    {
        // TODO uncomment below to declare an instance variable for ZacksTargetPriceConsensus
        //private ZacksTargetPriceConsensus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksTargetPriceConsensus
            //instance = new ZacksTargetPriceConsensus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksTargetPriceConsensus
        /// </summary>
        [Test]
        public void ZacksTargetPriceConsensusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksTargetPriceConsensus
            //Assert.IsInstanceOfType<ZacksTargetPriceConsensus> (instance, "variable 'instance' is a ZacksTargetPriceConsensus");
        }


        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'IndustryGroupNumber'
        /// </summary>
        [Test]
        public void IndustryGroupNumberTest()
        {
            // TODO unit test for the property 'IndustryGroupNumber'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Test]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Test]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Test]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }
        /// <summary>
        /// Test the property 'StandardDeviation'
        /// </summary>
        [Test]
        public void StandardDeviationTest()
        {
            // TODO unit test for the property 'StandardDeviation'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'MostRecentDate'
        /// </summary>
        [Test]
        public void MostRecentDateTest()
        {
            // TODO unit test for the property 'MostRecentDate'
        }
        /// <summary>
        /// Test the property 'Median'
        /// </summary>
        [Test]
        public void MedianTest()
        {
            // TODO unit test for the property 'Median'
        }
        /// <summary>
        /// Test the property 'Raised'
        /// </summary>
        [Test]
        public void RaisedTest()
        {
            // TODO unit test for the property 'Raised'
        }
        /// <summary>
        /// Test the property 'Lowered'
        /// </summary>
        [Test]
        public void LoweredTest()
        {
            // TODO unit test for the property 'Lowered'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

    }

}
