


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksETFHolding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksETFHoldingTests
    {
        // TODO uncomment below to declare an instance variable for ZacksETFHolding
        //private ZacksETFHolding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksETFHolding
            //instance = new ZacksETFHolding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksETFHolding
        /// </summary>
        [Test]
        public void ZacksETFHoldingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksETFHolding
            //Assert.IsInstanceOfType<ZacksETFHolding> (instance, "variable 'instance' is a ZacksETFHolding");
        }


        /// <summary>
        /// Test the property 'EtfTicker'
        /// </summary>
        [Test]
        public void EtfTickerTest()
        {
            // TODO unit test for the property 'EtfTicker'
        }
        /// <summary>
        /// Test the property 'EtfName'
        /// </summary>
        [Test]
        public void EtfNameTest()
        {
            // TODO unit test for the property 'EtfName'
        }
        /// <summary>
        /// Test the property 'HoldingSymbol'
        /// </summary>
        [Test]
        public void HoldingSymbolTest()
        {
            // TODO unit test for the property 'HoldingSymbol'
        }
        /// <summary>
        /// Test the property 'HoldingName'
        /// </summary>
        [Test]
        public void HoldingNameTest()
        {
            // TODO unit test for the property 'HoldingName'
        }
        /// <summary>
        /// Test the property 'DateOfHolding'
        /// </summary>
        [Test]
        public void DateOfHoldingTest()
        {
            // TODO unit test for the property 'DateOfHolding'
        }
        /// <summary>
        /// Test the property 'Shares'
        /// </summary>
        [Test]
        public void SharesTest()
        {
            // TODO unit test for the property 'Shares'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

    }

}
