


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksInstitutionalHoldingHistoricalSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksInstitutionalHoldingHistoricalSummaryTests
    {
        // TODO uncomment below to declare an instance variable for ZacksInstitutionalHoldingHistoricalSummary
        //private ZacksInstitutionalHoldingHistoricalSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksInstitutionalHoldingHistoricalSummary
            //instance = new ZacksInstitutionalHoldingHistoricalSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksInstitutionalHoldingHistoricalSummary
        /// </summary>
        [Test]
        public void ZacksInstitutionalHoldingHistoricalSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksInstitutionalHoldingHistoricalSummary
            //Assert.IsInstanceOfType<ZacksInstitutionalHoldingHistoricalSummary> (instance, "variable 'instance' is a ZacksInstitutionalHoldingHistoricalSummary");
        }


        /// <summary>
        /// Test the property 'AsOfDate'
        /// </summary>
        [Test]
        public void AsOfDateTest()
        {
            // TODO unit test for the property 'AsOfDate'
        }
        /// <summary>
        /// Test the property 'SharesHeld'
        /// </summary>
        [Test]
        public void SharesHeldTest()
        {
            // TODO unit test for the property 'SharesHeld'
        }

    }

}
