


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.SDK.Api;
using Intrinio.SDK.Model;
using Intrinio.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.SDK.Test
{
    /// <summary>
    ///  Class for testing ZacksEPSSurpriseSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZacksEPSSurpriseSummaryTests
    {
        // TODO uncomment below to declare an instance variable for ZacksEPSSurpriseSummary
        //private ZacksEPSSurpriseSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZacksEPSSurpriseSummary
            //instance = new ZacksEPSSurpriseSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZacksEPSSurpriseSummary
        /// </summary>
        [Test]
        public void ZacksEPSSurpriseSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZacksEPSSurpriseSummary
            //Assert.IsInstanceOfType<ZacksEPSSurpriseSummary> (instance, "variable 'instance' is a ZacksEPSSurpriseSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FiscalYear'
        /// </summary>
        [Test]
        public void FiscalYearTest()
        {
            // TODO unit test for the property 'FiscalYear'
        }
        /// <summary>
        /// Test the property 'FiscalQuarter'
        /// </summary>
        [Test]
        public void FiscalQuarterTest()
        {
            // TODO unit test for the property 'FiscalQuarter'
        }
        /// <summary>
        /// Test the property 'CalendarYear'
        /// </summary>
        [Test]
        public void CalendarYearTest()
        {
            // TODO unit test for the property 'CalendarYear'
        }
        /// <summary>
        /// Test the property 'CalendarQuarter'
        /// </summary>
        [Test]
        public void CalendarQuarterTest()
        {
            // TODO unit test for the property 'CalendarQuarter'
        }
        /// <summary>
        /// Test the property 'ActualReportedDate'
        /// </summary>
        [Test]
        public void ActualReportedDateTest()
        {
            // TODO unit test for the property 'ActualReportedDate'
        }
        /// <summary>
        /// Test the property 'ActualReportedTime'
        /// </summary>
        [Test]
        public void ActualReportedTimeTest()
        {
            // TODO unit test for the property 'ActualReportedTime'
        }
        /// <summary>
        /// Test the property 'ActualReportedCode'
        /// </summary>
        [Test]
        public void ActualReportedCodeTest()
        {
            // TODO unit test for the property 'ActualReportedCode'
        }
        /// <summary>
        /// Test the property 'ActualReportedDesc'
        /// </summary>
        [Test]
        public void ActualReportedDescTest()
        {
            // TODO unit test for the property 'ActualReportedDesc'
        }
        /// <summary>
        /// Test the property 'EpsActual'
        /// </summary>
        [Test]
        public void EpsActualTest()
        {
            // TODO unit test for the property 'EpsActual'
        }
        /// <summary>
        /// Test the property 'EpsActualZacksAdj'
        /// </summary>
        [Test]
        public void EpsActualZacksAdjTest()
        {
            // TODO unit test for the property 'EpsActualZacksAdj'
        }
        /// <summary>
        /// Test the property 'EpsMeanEstimate'
        /// </summary>
        [Test]
        public void EpsMeanEstimateTest()
        {
            // TODO unit test for the property 'EpsMeanEstimate'
        }
        /// <summary>
        /// Test the property 'EpsAmountDiff'
        /// </summary>
        [Test]
        public void EpsAmountDiffTest()
        {
            // TODO unit test for the property 'EpsAmountDiff'
        }
        /// <summary>
        /// Test the property 'EpsPercentDiff'
        /// </summary>
        [Test]
        public void EpsPercentDiffTest()
        {
            // TODO unit test for the property 'EpsPercentDiff'
        }
        /// <summary>
        /// Test the property 'EpsCountEstimate'
        /// </summary>
        [Test]
        public void EpsCountEstimateTest()
        {
            // TODO unit test for the property 'EpsCountEstimate'
        }
        /// <summary>
        /// Test the property 'EpsStdDevEstimate'
        /// </summary>
        [Test]
        public void EpsStdDevEstimateTest()
        {
            // TODO unit test for the property 'EpsStdDevEstimate'
        }

    }

}
