


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing ApiResponseHistoricalData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseHistoricalDataTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseHistoricalData
        //private ApiResponseHistoricalData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseHistoricalData
            //instance = new ApiResponseHistoricalData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseHistoricalData
        /// </summary>
        [Test]
        public void ApiResponseHistoricalDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseHistoricalData
            //Assert.IsInstanceOfType<ApiResponseHistoricalData> (instance, "variable 'instance' is a ApiResponseHistoricalData");
        }


        /// <summary>
        /// Test the property 'HistoricalData'
        /// </summary>
        [Test]
        public void HistoricalDataTest()
        {
            // TODO unit test for the property 'HistoricalData'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
