


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing ApiResponseSecurityStockPriceAdjustments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiResponseSecurityStockPriceAdjustmentsTests
    {
        // TODO uncomment below to declare an instance variable for ApiResponseSecurityStockPriceAdjustments
        //private ApiResponseSecurityStockPriceAdjustments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiResponseSecurityStockPriceAdjustments
            //instance = new ApiResponseSecurityStockPriceAdjustments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiResponseSecurityStockPriceAdjustments
        /// </summary>
        [Test]
        public void ApiResponseSecurityStockPriceAdjustmentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiResponseSecurityStockPriceAdjustments
            //Assert.IsInstanceOfType<ApiResponseSecurityStockPriceAdjustments> (instance, "variable 'instance' is a ApiResponseSecurityStockPriceAdjustments");
        }


        /// <summary>
        /// Test the property 'StockPriceAdjustments'
        /// </summary>
        [Test]
        public void StockPriceAdjustmentsTest()
        {
            // TODO unit test for the property 'StockPriceAdjustments'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
