


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing DataPointText
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataPointTextTests
    {
        // TODO uncomment below to declare an instance variable for DataPointText
        //private DataPointText instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataPointText
            //instance = new DataPointText();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataPointText
        /// </summary>
        [Test]
        public void DataPointTextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataPointText
            //Assert.IsInstanceOfType<DataPointText> (instance, "variable 'instance' is a DataPointText");
        }



    }

}
