


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing FundamentalSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FundamentalSummaryTests
    {
        // TODO uncomment below to declare an instance variable for FundamentalSummary
        //private FundamentalSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FundamentalSummary
            //instance = new FundamentalSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FundamentalSummary
        /// </summary>
        [Test]
        public void FundamentalSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FundamentalSummary
            //Assert.IsInstanceOfType<FundamentalSummary> (instance, "variable 'instance' is a FundamentalSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StatementCode'
        /// </summary>
        [Test]
        public void StatementCodeTest()
        {
            // TODO unit test for the property 'StatementCode'
        }
        /// <summary>
        /// Test the property 'FiscalYear'
        /// </summary>
        [Test]
        public void FiscalYearTest()
        {
            // TODO unit test for the property 'FiscalYear'
        }
        /// <summary>
        /// Test the property 'FiscalPeriod'
        /// </summary>
        [Test]
        public void FiscalPeriodTest()
        {
            // TODO unit test for the property 'FiscalPeriod'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'FilingDate'
        /// </summary>
        [Test]
        public void FilingDateTest()
        {
            // TODO unit test for the property 'FilingDate'
        }

    }

}
