


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20023
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20023Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20023
        //private InlineResponse20023 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20023
            //instance = new InlineResponse20023();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20023
        /// </summary>
        [Test]
        public void InlineResponse20023InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20023
            //Assert.IsInstanceOfType<InlineResponse20023> (instance, "variable 'instance' is a InlineResponse20023");
        }


        /// <summary>
        /// Test the property 'Securities'
        /// </summary>
        [Test]
        public void SecuritiesTest()
        {
            // TODO unit test for the property 'Securities'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
