


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20018
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20018Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20018
        //private InlineResponse20018 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20018
            //instance = new InlineResponse20018();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20018
        /// </summary>
        [Test]
        public void InlineResponse20018InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20018
            //Assert.IsInstanceOfType<InlineResponse20018> (instance, "variable 'instance' is a InlineResponse20018");
        }


        /// <summary>
        /// Test the property 'Indices'
        /// </summary>
        [Test]
        public void IndicesTest()
        {
            // TODO unit test for the property 'Indices'
        }

    }

}
