


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20026
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20026Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20026
        //private InlineResponse20026 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20026
            //instance = new InlineResponse20026();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20026
        /// </summary>
        [Test]
        public void InlineResponse20026InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20026
            //Assert.IsInstanceOfType<InlineResponse20026> (instance, "variable 'instance' is a InlineResponse20026");
        }


        /// <summary>
        /// Test the property 'StockPrices'
        /// </summary>
        [Test]
        public void StockPricesTest()
        {
            // TODO unit test for the property 'StockPrices'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
