


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2001
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2001Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001
        //private InlineResponse2001 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2001
            //instance = new InlineResponse2001();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2001
        /// </summary>
        [Test]
        public void InlineResponse2001InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2001
            //Assert.IsInstanceOfType<InlineResponse2001> (instance, "variable 'instance' is a InlineResponse2001");
        }


        /// <summary>
        /// Test the property 'News'
        /// </summary>
        [Test]
        public void NewsTest()
        {
            // TODO unit test for the property 'News'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
