


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20020
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20020Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20020
        //private InlineResponse20020 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20020
            //instance = new InlineResponse20020();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20020
        /// </summary>
        [Test]
        public void InlineResponse20020InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20020
            //Assert.IsInstanceOfType<InlineResponse20020> (instance, "variable 'instance' is a InlineResponse20020");
        }


        /// <summary>
        /// Test the property 'Indices'
        /// </summary>
        [Test]
        public void IndicesTest()
        {
            // TODO unit test for the property 'Indices'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
