


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20022
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20022Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20022
        //private InlineResponse20022 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20022
            //instance = new InlineResponse20022();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20022
        /// </summary>
        [Test]
        public void InlineResponse20022InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20022
            //Assert.IsInstanceOfType<InlineResponse20022> (instance, "variable 'instance' is a InlineResponse20022");
        }


        /// <summary>
        /// Test the property 'HistoricalData'
        /// </summary>
        [Test]
        public void HistoricalDataTest()
        {
            // TODO unit test for the property 'HistoricalData'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }

    }

}
