


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing MutualFund
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MutualFundTests
    {
        // TODO uncomment below to declare an instance variable for MutualFund
        //private MutualFund instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MutualFund
            //instance = new MutualFund();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MutualFund
        /// </summary>
        [Test]
        public void MutualFundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MutualFund
            //Assert.IsInstanceOfType<MutualFund> (instance, "variable 'instance' is a MutualFund");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Cusip'
        /// </summary>
        [Test]
        public void CusipTest()
        {
            // TODO unit test for the property 'Cusip'
        }
        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Test]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }

    }

}
