


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing SecuritySummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecuritySummaryTests
    {
        // TODO uncomment below to declare an instance variable for SecuritySummary
        //private SecuritySummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecuritySummary
            //instance = new SecuritySummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecuritySummary
        /// </summary>
        [Test]
        public void SecuritySummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecuritySummary
            //Assert.IsInstanceOfType<SecuritySummary> (instance, "variable 'instance' is a SecuritySummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'CompositeTicker'
        /// </summary>
        [Test]
        public void CompositeTickerTest()
        {
            // TODO unit test for the property 'CompositeTicker'
        }
        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'CompositeFigi'
        /// </summary>
        [Test]
        public void CompositeFigiTest()
        {
            // TODO unit test for the property 'CompositeFigi'
        }
        /// <summary>
        /// Test the property 'ShareClassFigi'
        /// </summary>
        [Test]
        public void ShareClassFigiTest()
        {
            // TODO unit test for the property 'ShareClassFigi'
        }

    }

}
