


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing SecurityScreenResultData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityScreenResultDataTests
    {
        // TODO uncomment below to declare an instance variable for SecurityScreenResultData
        //private SecurityScreenResultData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecurityScreenResultData
            //instance = new SecurityScreenResultData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecurityScreenResultData
        /// </summary>
        [Test]
        public void SecurityScreenResultDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecurityScreenResultData
            //Assert.IsInstanceOfType<SecurityScreenResultData> (instance, "variable 'instance' is a SecurityScreenResultData");
        }


        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'NumberValue'
        /// </summary>
        [Test]
        public void NumberValueTest()
        {
            // TODO unit test for the property 'NumberValue'
        }
        /// <summary>
        /// Test the property 'TextValue'
        /// </summary>
        [Test]
        public void TextValueTest()
        {
            // TODO unit test for the property 'TextValue'
        }

    }

}
