/* 
 * Intrinio API
 *
 * Welcome to the Intrinio API! Through our Marketplace, we offer a wide selection of financial data feeds sourced by our own proprietary processes as well as from many data vendors. The primary application of the Intrinio API is for use in third-party applications and integrations or for end-users utilizing the Excel add-in and Google Sheets add-on. The Intrinio API uses HTTPS verbs and a RESTful endpoint structure, which makes it easy to request data from Intrinio. Responses are delivered in JSON format. If you need additional help in using the API, go to our home page (https://intrinio.com) and click on the chat icon in the lower right corner.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing Security
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityTests
    {
        // TODO uncomment below to declare an instance variable for Security
        //private Security instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Security
            //instance = new Security();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Security
        /// </summary>
        [Test]
        public void SecurityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Security
            //Assert.IsInstanceOfType<Security> (instance, "variable 'instance' is a Security");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'ShareClass'
        /// </summary>
        [Test]
        public void ShareClassTest()
        {
            // TODO unit test for the property 'ShareClass'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'RoundLotSize'
        /// </summary>
        [Test]
        public void RoundLotSizeTest()
        {
            // TODO unit test for the property 'RoundLotSize'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'ExchangeTicker'
        /// </summary>
        [Test]
        public void ExchangeTickerTest()
        {
            // TODO unit test for the property 'ExchangeTicker'
        }
        /// <summary>
        /// Test the property 'CompositeTicker'
        /// </summary>
        [Test]
        public void CompositeTickerTest()
        {
            // TODO unit test for the property 'CompositeTicker'
        }
        /// <summary>
        /// Test the property 'AlternateTickers'
        /// </summary>
        [Test]
        public void AlternateTickersTest()
        {
            // TODO unit test for the property 'AlternateTickers'
        }
        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'CompositeFigi'
        /// </summary>
        [Test]
        public void CompositeFigiTest()
        {
            // TODO unit test for the property 'CompositeFigi'
        }
        /// <summary>
        /// Test the property 'ShareClassFigi'
        /// </summary>
        [Test]
        public void ShareClassFigiTest()
        {
            // TODO unit test for the property 'ShareClassFigi'
        }
        /// <summary>
        /// Test the property 'FigiUniqueid'
        /// </summary>
        [Test]
        public void FigiUniqueidTest()
        {
            // TODO unit test for the property 'FigiUniqueid'
        }
        /// <summary>
        /// Test the property 'Isin'
        /// </summary>
        [Test]
        public void IsinTest()
        {
            // TODO unit test for the property 'Isin'
        }
        /// <summary>
        /// Test the property 'Cusip'
        /// </summary>
        [Test]
        public void CusipTest()
        {
            // TODO unit test for the property 'Cusip'
        }
        /// <summary>
        /// Test the property 'Sedol'
        /// </summary>
        [Test]
        public void SedolTest()
        {
            // TODO unit test for the property 'Sedol'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Etf'
        /// </summary>
        [Test]
        public void EtfTest()
        {
            // TODO unit test for the property 'Etf'
        }
        /// <summary>
        /// Test the property 'Delisted'
        /// </summary>
        [Test]
        public void DelistedTest()
        {
            // TODO unit test for the property 'Delisted'
        }
        /// <summary>
        /// Test the property 'PrimaryListing'
        /// </summary>
        [Test]
        public void PrimaryListingTest()
        {
            // TODO unit test for the property 'PrimaryListing'
        }
        /// <summary>
        /// Test the property 'PrimarySecurity'
        /// </summary>
        [Test]
        public void PrimarySecurityTest()
        {
            // TODO unit test for the property 'PrimarySecurity'
        }
        /// <summary>
        /// Test the property 'FirstStockPrice'
        /// </summary>
        [Test]
        public void FirstStockPriceTest()
        {
            // TODO unit test for the property 'FirstStockPrice'
        }
        /// <summary>
        /// Test the property 'LastStockPrice'
        /// </summary>
        [Test]
        public void LastStockPriceTest()
        {
            // TODO unit test for the property 'LastStockPrice'
        }
        /// <summary>
        /// Test the property 'LastStockPriceAdjustment'
        /// </summary>
        [Test]
        public void LastStockPriceAdjustmentTest()
        {
            // TODO unit test for the property 'LastStockPriceAdjustment'
        }
        /// <summary>
        /// Test the property 'LastCorporateAction'
        /// </summary>
        [Test]
        public void LastCorporateActionTest()
        {
            // TODO unit test for the property 'LastCorporateAction'
        }

    }

}
