


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Intrinio.Api;
using Intrinio.Model;
using Intrinio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Intrinio.Test
{
    /// <summary>
    ///  Class for testing StockMarketIndexSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StockMarketIndexSummaryTests
    {
        // TODO uncomment below to declare an instance variable for StockMarketIndexSummary
        //private StockMarketIndexSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StockMarketIndexSummary
            //instance = new StockMarketIndexSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StockMarketIndexSummary
        /// </summary>
        [Test]
        public void StockMarketIndexSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StockMarketIndexSummary
            //Assert.IsInstanceOfType<StockMarketIndexSummary> (instance, "variable 'instance' is a StockMarketIndexSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Continent'
        /// </summary>
        [Test]
        public void ContinentTest()
        {
            // TODO unit test for the property 'Continent'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'UpdateFrequency'
        /// </summary>
        [Test]
        public void UpdateFrequencyTest()
        {
            // TODO unit test for the property 'UpdateFrequency'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'ObservationStart'
        /// </summary>
        [Test]
        public void ObservationStartTest()
        {
            // TODO unit test for the property 'ObservationStart'
        }
        /// <summary>
        /// Test the property 'ObservationEnd'
        /// </summary>
        [Test]
        public void ObservationEndTest()
        {
            // TODO unit test for the property 'ObservationEnd'
        }

    }

}
